<?php

namespace AppBundle\Form\Type;

use Application\Sonata\MediaBundle\Entity\Media;
use Sonata\AdminBundle\Form\Type\ModelHiddenType;
use Sonata\MediaBundle\Twig\Extension\MediaExtension;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class GifGeneratorType extends ModelHiddenType
{
    /**
     * @var MediaExtension
     */
    private $mediaExtension;

    public function __construct(MediaExtension $mediaExtension)
    {
        $this->mediaExtension = $mediaExtension;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'imagesSelector' => null,
            'mediaIdsSelector' => null,
        ]);
    }


    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        /** @var Media $media */
        $media = $view->vars['data'];
        $view->vars['imagesSelector'] = $options['imagesSelector'];
        $view->vars['mediaIdsSelector'] = $options['mediaIdsSelector'];
        $view->vars['originalValue'] = ($media)
            ?   [
                'id' => $media->getId(),
                'url' => $this->mediaExtension->path($media, 'reference'),
            ]
            : null;
    }

    public function getParent()
    {
        return 'hidden'; // TODO: Change the autogenerated stub
    }

    public function getName()
    {
        return 'gif_generator';
    }
}
