<?php

namespace AppBundle\Admin;

use AppBundle\Admin\Form\PrivateUrlTrait;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Route\RouteCollection;

class DraftAdmin extends BaseAdmin
{
    use PrivateUrlTrait;

    public function createQuery($context = 'list')
    {

        return parent::createQuery($context); // TODO: Change the autogenerated stub
    }


    public function generateObjectUrl($name, $object, array $parameters = array(), $absolute = false)
    {
        $parameters['id'] = $object->getOwnerEntityId();

        return $this->generateUrl($name, $parameters, $absolute);
    }

    public function getBatchActions()
    {
        $actions = parent::getBatchActions();
        unset($actions['delete']);

        return $actions;
    }

    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ->addIdentifier('title')
            ->add('label', 'text', ['label' => 'Тип контента'])
        ;

        $this->setTemplate('base_list_field', ':Admin:Draft/draft_list_field.html.twig');
    }

    protected function configureRoutes(RouteCollection $collection)
    {
        $collection->remove('delete');
        $collection->remove('create');
        $collection->remove('export');
        $collection->remove('show');
    }
}
