<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20151122195250 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE related_i_document_posts_post_documents (document_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_3C722E6FC33F7837 (document_id), INDEX IDX_3C722E6F4B89032C (post_id), PRIMARY KEY(document_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_document_infographics_infographics_documents (document_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_CFAA0E77C33F7837 (document_id), INDEX IDX_CFAA0E7795A8ED8C (infographics_id), PRIMARY KEY(document_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_document_galleries_gallery_documents (document_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_452FCFAEC33F7837 (document_id), INDEX IDX_452FCFAE4E7AF8F (gallery_id), PRIMARY KEY(document_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_document_videos_video_documents (document_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_4AB912F3C33F7837 (document_id), INDEX IDX_4AB912F329C1004E (video_id), PRIMARY KEY(document_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_document_metro_stations_metro_station (document_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_BB49C9E0C33F7837 (document_id), INDEX IDX_BB49C9E0F7D58AAA (metro_station_id), PRIMARY KEY(document_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_document_roads_road (document_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_5A863E26C33F7837 (document_id), INDEX IDX_5A863E26962F8178 (road_id), PRIMARY KEY(document_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_document_documents_document (document_source INT NOT NULL, document_target INT NOT NULL, INDEX IDX_64759093E1E8CE15 (document_source), INDEX IDX_64759093F80D9E9A (document_target), PRIMARY KEY(document_source, document_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_posts_post (stadium_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_64A0A86C7E860E36 (stadium_id), INDEX IDX_64A0A86C4B89032C (post_id), PRIMARY KEY(stadium_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_infographics_infographics (stadium_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_746909647E860E36 (stadium_id), INDEX IDX_7469096495A8ED8C (infographics_id), PRIMARY KEY(stadium_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_galleries_gallery (stadium_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_9CA8E8697E860E36 (stadium_id), INDEX IDX_9CA8E8694E7AF8F (gallery_id), PRIMARY KEY(stadium_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_videos_video (stadium_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_77DB18127E860E36 (stadium_id), INDEX IDX_77DB181229C1004E (video_id), PRIMARY KEY(stadium_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_constructions_construction (stadium_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_E2A324D77E860E36 (stadium_id), INDEX IDX_E2A324D7CF48117A (construction_id), PRIMARY KEY(stadium_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_metro_stations_metro_station (stadium_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_8FACD0CF7E860E36 (stadium_id), INDEX IDX_8FACD0CFF7D58AAA (metro_station_id), PRIMARY KEY(stadium_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_roads_road (stadium_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_F65F7AF57E860E36 (stadium_id), INDEX IDX_F65F7AF5962F8178 (road_id), PRIMARY KEY(stadium_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_stadium_documents_document (stadium_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_DC458F767E860E36 (stadium_id), INDEX IDX_DC458F76C33F7837 (document_id), PRIMARY KEY(stadium_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_gallery_posts_post_galleries (gallery_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_741F20474E7AF8F (gallery_id), INDEX IDX_741F20474B89032C (post_id), PRIMARY KEY(gallery_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_gallery_infographics_infographics_galleries (gallery_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_4436E8664E7AF8F (gallery_id), INDEX IDX_4436E86695A8ED8C (infographics_id), PRIMARY KEY(gallery_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_gallery_galleries_gallery (gallery_source INT NOT NULL, gallery_target INT NOT NULL, INDEX IDX_A6FAB26EFD0993D1 (gallery_source), INDEX IDX_A6FAB26EE4ECC35E (gallery_target), PRIMARY KEY(gallery_source, gallery_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_gallery_videos_video_galleries (gallery_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_E93DE6C14E7AF8F (gallery_id), INDEX IDX_E93DE6C129C1004E (video_id), PRIMARY KEY(gallery_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_gallery_metro_stations_metro_station (gallery_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_4008F5884E7AF8F (gallery_id), INDEX IDX_4008F588F7D58AAA (metro_station_id), PRIMARY KEY(gallery_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_gallery_roads_road (gallery_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_AEF04B324E7AF8F (gallery_id), INDEX IDX_AEF04B32962F8178 (road_id), PRIMARY KEY(gallery_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_construction_posts_post_constructions (construction_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_9C7251E9CF48117A (construction_id), INDEX IDX_9C7251E94B89032C (post_id), PRIMARY KEY(construction_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_construction_infographics_infographics_constructions (construction_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_63DEC255CF48117A (construction_id), INDEX IDX_63DEC25595A8ED8C (infographics_id), PRIMARY KEY(construction_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_construction_galleries_gallery_constructions (construction_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_43322BECF48117A (construction_id), INDEX IDX_43322BE4E7AF8F (gallery_id), PRIMARY KEY(construction_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_construction_videos_video_constructions (construction_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_35BFE994CF48117A (construction_id), INDEX IDX_35BFE99429C1004E (video_id), PRIMARY KEY(construction_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_construction_constructions_construction (construction_source INT NOT NULL, construction_target INT NOT NULL, INDEX IDX_2C9AF081A6581D40 (construction_source), INDEX IDX_2C9AF081BFBD4DCF (construction_target), PRIMARY KEY(construction_source, construction_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_construction_metro_stations_metro_station (construction_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_E2F3F2E9CF48117A (construction_id), INDEX IDX_E2F3F2E9F7D58AAA (metro_station_id), PRIMARY KEY(construction_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_construction_roads_road (construction_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_968264F0CF48117A (construction_id), INDEX IDX_968264F0962F8178 (road_id), PRIMARY KEY(construction_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_construction_documents_document_constructions (construction_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_DCD4803BCF48117A (construction_id), INDEX IDX_DCD4803BC33F7837 (document_id), PRIMARY KEY(construction_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_post_posts_post (post_source INT NOT NULL, post_target INT NOT NULL, INDEX IDX_4ECA09DC6FA89B16 (post_source), INDEX IDX_4ECA09DC764DCB99 (post_target), PRIMARY KEY(post_source, post_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_post_videos_video_posts (post_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_513D546C4B89032C (post_id), INDEX IDX_513D546C29C1004E (video_id), PRIMARY KEY(post_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_post_metro_stations_metro_station (post_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_639394144B89032C (post_id), INDEX IDX_63939414F7D58AAA (metro_station_id), PRIMARY KEY(post_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_post_roads_road (post_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_DC35DB454B89032C (post_id), INDEX IDX_DC35DB45962F8178 (road_id), PRIMARY KEY(post_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_video_videos_video (video_source INT NOT NULL, video_target INT NOT NULL, INDEX IDX_D47FE9C367DDDFBE (video_source), INDEX IDX_D47FE9C37E388F31 (video_target), PRIMARY KEY(video_source, video_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_video_metro_stations_metro_station (video_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_BD258F3C29C1004E (video_id), INDEX IDX_BD258F3CF7D58AAA (metro_station_id), PRIMARY KEY(video_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_video_roads_road (video_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_B0BD6F2229C1004E (video_id), INDEX IDX_B0BD6F22962F8178 (road_id), PRIMARY KEY(video_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_infographics_posts_post_infographics (infographics_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_7298C98095A8ED8C (infographics_id), INDEX IDX_7298C9804B89032C (post_id), PRIMARY KEY(infographics_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_infographics_infographics_infographics (infographics_source INT NOT NULL, infographics_target INT NOT NULL, INDEX IDX_5EC242E06C4B9589 (infographics_source), INDEX IDX_5EC242E075AEC506 (infographics_target), PRIMARY KEY(infographics_source, infographics_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_i_infographics_videos_video_infographics (infographics_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_9D650A5B95A8ED8C (infographics_id), INDEX IDX_9D650A5B29C1004E (video_id), PRIMARY KEY(infographics_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_infographics_metro_stations_metro_station (infographics_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_3B198F1795A8ED8C (infographics_id), INDEX IDX_3B198F17F7D58AAA (metro_station_id), PRIMARY KEY(infographics_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_infographics_roads_road (infographics_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_68BFE57895A8ED8C (infographics_id), INDEX IDX_68BFE578962F8178 (road_id), PRIMARY KEY(infographics_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_posts_post (initiative_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_77FE3767AB7D9771 (initiative_id), INDEX IDX_77FE37674B89032C (post_id), PRIMARY KEY(initiative_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_infographics_infographics (initiative_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_9122CC2FAB7D9771 (initiative_id), INDEX IDX_9122CC2F95A8ED8C (infographics_id), PRIMARY KEY(initiative_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_galleries_gallery (initiative_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_B71091DEAB7D9771 (initiative_id), INDEX IDX_B71091DE4E7AF8F (gallery_id), PRIMARY KEY(initiative_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_videos_video (initiative_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_F49F5C52AB7D9771 (initiative_id), INDEX IDX_F49F5C5229C1004E (video_id), PRIMARY KEY(initiative_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_constructions_construction (initiative_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_348F70AAB7D9771 (initiative_id), INDEX IDX_348F70ACF48117A (construction_id), PRIMARY KEY(initiative_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_metro_stations_metro_station (initiative_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_A4E00918AB7D9771 (initiative_id), INDEX IDX_A4E00918F7D58AAA (metro_station_id), PRIMARY KEY(initiative_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_roads_road (initiative_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_E501E5FEAB7D9771 (initiative_id), INDEX IDX_E501E5FE962F8178 (road_id), PRIMARY KEY(initiative_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE related_initiative_documents_document (initiative_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_896B1120AB7D9771 (initiative_id), INDEX IDX_896B1120C33F7837 (document_id), PRIMARY KEY(initiative_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE related_i_document_posts_post_documents ADD CONSTRAINT FK_3C722E6FC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_document_posts_post_documents ADD CONSTRAINT FK_3C722E6F4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_document_infographics_infographics_documents ADD CONSTRAINT FK_CFAA0E77C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_document_infographics_infographics_documents ADD CONSTRAINT FK_CFAA0E7795A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_document_galleries_gallery_documents ADD CONSTRAINT FK_452FCFAEC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_document_galleries_gallery_documents ADD CONSTRAINT FK_452FCFAE4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_document_videos_video_documents ADD CONSTRAINT FK_4AB912F3C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_document_videos_video_documents ADD CONSTRAINT FK_4AB912F329C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_document_metro_stations_metro_station ADD CONSTRAINT FK_BB49C9E0C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_document_metro_stations_metro_station ADD CONSTRAINT FK_BB49C9E0F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_document_roads_road ADD CONSTRAINT FK_5A863E26C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_document_roads_road ADD CONSTRAINT FK_5A863E26962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_document_documents_document ADD CONSTRAINT FK_64759093E1E8CE15 FOREIGN KEY (document_source) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_document_documents_document ADD CONSTRAINT FK_64759093F80D9E9A FOREIGN KEY (document_target) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_posts_post ADD CONSTRAINT FK_64A0A86C7E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_posts_post ADD CONSTRAINT FK_64A0A86C4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_infographics_infographics ADD CONSTRAINT FK_746909647E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_infographics_infographics ADD CONSTRAINT FK_7469096495A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_galleries_gallery ADD CONSTRAINT FK_9CA8E8697E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_galleries_gallery ADD CONSTRAINT FK_9CA8E8694E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_videos_video ADD CONSTRAINT FK_77DB18127E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_videos_video ADD CONSTRAINT FK_77DB181229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_constructions_construction ADD CONSTRAINT FK_E2A324D77E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_constructions_construction ADD CONSTRAINT FK_E2A324D7CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_metro_stations_metro_station ADD CONSTRAINT FK_8FACD0CF7E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_metro_stations_metro_station ADD CONSTRAINT FK_8FACD0CFF7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_roads_road ADD CONSTRAINT FK_F65F7AF57E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_roads_road ADD CONSTRAINT FK_F65F7AF5962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_documents_document ADD CONSTRAINT FK_DC458F767E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_stadium_documents_document ADD CONSTRAINT FK_DC458F76C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_gallery_posts_post_galleries ADD CONSTRAINT FK_741F20474E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_gallery_posts_post_galleries ADD CONSTRAINT FK_741F20474B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_gallery_infographics_infographics_galleries ADD CONSTRAINT FK_4436E8664E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_gallery_infographics_infographics_galleries ADD CONSTRAINT FK_4436E86695A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_gallery_galleries_gallery ADD CONSTRAINT FK_A6FAB26EFD0993D1 FOREIGN KEY (gallery_source) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_gallery_galleries_gallery ADD CONSTRAINT FK_A6FAB26EE4ECC35E FOREIGN KEY (gallery_target) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_gallery_videos_video_galleries ADD CONSTRAINT FK_E93DE6C14E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_gallery_videos_video_galleries ADD CONSTRAINT FK_E93DE6C129C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_gallery_metro_stations_metro_station ADD CONSTRAINT FK_4008F5884E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_gallery_metro_stations_metro_station ADD CONSTRAINT FK_4008F588F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_gallery_roads_road ADD CONSTRAINT FK_AEF04B324E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_gallery_roads_road ADD CONSTRAINT FK_AEF04B32962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_posts_post_constructions ADD CONSTRAINT FK_9C7251E9CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_posts_post_constructions ADD CONSTRAINT FK_9C7251E94B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_infographics_infographics_constructions ADD CONSTRAINT FK_63DEC255CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_infographics_infographics_constructions ADD CONSTRAINT FK_63DEC25595A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_galleries_gallery_constructions ADD CONSTRAINT FK_43322BECF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_galleries_gallery_constructions ADD CONSTRAINT FK_43322BE4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_videos_video_constructions ADD CONSTRAINT FK_35BFE994CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_videos_video_constructions ADD CONSTRAINT FK_35BFE99429C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_construction_constructions_construction ADD CONSTRAINT FK_2C9AF081A6581D40 FOREIGN KEY (construction_source) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_construction_constructions_construction ADD CONSTRAINT FK_2C9AF081BFBD4DCF FOREIGN KEY (construction_target) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_construction_metro_stations_metro_station ADD CONSTRAINT FK_E2F3F2E9CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_construction_metro_stations_metro_station ADD CONSTRAINT FK_E2F3F2E9F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_construction_roads_road ADD CONSTRAINT FK_968264F0CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_construction_roads_road ADD CONSTRAINT FK_968264F0962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_documents_document_constructions ADD CONSTRAINT FK_DCD4803BCF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_construction_documents_document_constructions ADD CONSTRAINT FK_DCD4803BC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_post_posts_post ADD CONSTRAINT FK_4ECA09DC6FA89B16 FOREIGN KEY (post_source) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_post_posts_post ADD CONSTRAINT FK_4ECA09DC764DCB99 FOREIGN KEY (post_target) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_post_videos_video_posts ADD CONSTRAINT FK_513D546C4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_post_videos_video_posts ADD CONSTRAINT FK_513D546C29C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_post_metro_stations_metro_station ADD CONSTRAINT FK_639394144B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_post_metro_stations_metro_station ADD CONSTRAINT FK_63939414F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_post_roads_road ADD CONSTRAINT FK_DC35DB454B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_post_roads_road ADD CONSTRAINT FK_DC35DB45962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_video_videos_video ADD CONSTRAINT FK_D47FE9C367DDDFBE FOREIGN KEY (video_source) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_video_videos_video ADD CONSTRAINT FK_D47FE9C37E388F31 FOREIGN KEY (video_target) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_video_metro_stations_metro_station ADD CONSTRAINT FK_BD258F3C29C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_video_metro_stations_metro_station ADD CONSTRAINT FK_BD258F3CF7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_video_roads_road ADD CONSTRAINT FK_B0BD6F2229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_video_roads_road ADD CONSTRAINT FK_B0BD6F22962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_infographics_posts_post_infographics ADD CONSTRAINT FK_7298C98095A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_infographics_posts_post_infographics ADD CONSTRAINT FK_7298C9804B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_infographics_infographics_infographics ADD CONSTRAINT FK_5EC242E06C4B9589 FOREIGN KEY (infographics_source) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_infographics_infographics_infographics ADD CONSTRAINT FK_5EC242E075AEC506 FOREIGN KEY (infographics_target) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_infographics_videos_video_infographics ADD CONSTRAINT FK_9D650A5B95A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_i_infographics_videos_video_infographics ADD CONSTRAINT FK_9D650A5B29C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_infographics_metro_stations_metro_station ADD CONSTRAINT FK_3B198F1795A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_infographics_metro_stations_metro_station ADD CONSTRAINT FK_3B198F17F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_infographics_roads_road ADD CONSTRAINT FK_68BFE57895A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_infographics_roads_road ADD CONSTRAINT FK_68BFE578962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_posts_post ADD CONSTRAINT FK_77FE3767AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_posts_post ADD CONSTRAINT FK_77FE37674B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_infographics_infographics ADD CONSTRAINT FK_9122CC2FAB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_infographics_infographics ADD CONSTRAINT FK_9122CC2F95A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_galleries_gallery ADD CONSTRAINT FK_B71091DEAB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_galleries_gallery ADD CONSTRAINT FK_B71091DE4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_videos_video ADD CONSTRAINT FK_F49F5C52AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_videos_video ADD CONSTRAINT FK_F49F5C5229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_constructions_construction ADD CONSTRAINT FK_348F70AAB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_constructions_construction ADD CONSTRAINT FK_348F70ACF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_metro_stations_metro_station ADD CONSTRAINT FK_A4E00918AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_metro_stations_metro_station ADD CONSTRAINT FK_A4E00918F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_roads_road ADD CONSTRAINT FK_E501E5FEAB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_roads_road ADD CONSTRAINT FK_E501E5FE962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_documents_document ADD CONSTRAINT FK_896B1120AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE related_initiative_documents_document ADD CONSTRAINT FK_896B1120C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE construction_related_constructions_construction');
        $this->addSql('DROP TABLE construction_related_documents_document');
        $this->addSql('DROP TABLE construction_related_galleries_gallery');
        $this->addSql('DROP TABLE construction_related_infographics_infographics');
        $this->addSql('DROP TABLE construction_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE construction_related_posts_post');
        $this->addSql('DROP TABLE construction_related_press_releases_post');
        $this->addSql('DROP TABLE construction_related_roads_road');
        $this->addSql('DROP TABLE construction_related_videos_video');
        $this->addSql('DROP TABLE document_related_constructions_construction');
        $this->addSql('DROP TABLE document_related_documents_document');
        $this->addSql('DROP TABLE document_related_galleries_gallery');
        $this->addSql('DROP TABLE document_related_infographics_infographics');
        $this->addSql('DROP TABLE document_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE document_related_posts_post');
        $this->addSql('DROP TABLE document_related_press_releases_post');
        $this->addSql('DROP TABLE document_related_roads_road');
        $this->addSql('DROP TABLE document_related_videos_video');
        $this->addSql('DROP TABLE gallery_related_constructions_construction');
        $this->addSql('DROP TABLE gallery_related_documents_document');
        $this->addSql('DROP TABLE gallery_related_galleries_gallery');
        $this->addSql('DROP TABLE gallery_related_infographics_infographics');
        $this->addSql('DROP TABLE gallery_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE gallery_related_posts_post');
        $this->addSql('DROP TABLE gallery_related_press_releases_post');
        $this->addSql('DROP TABLE gallery_related_roads_road');
        $this->addSql('DROP TABLE gallery_related_videos_video');
        $this->addSql('DROP TABLE infographics_related_constructions_construction');
        $this->addSql('DROP TABLE infographics_related_documents_document');
        $this->addSql('DROP TABLE infographics_related_galleries_gallery');
        $this->addSql('DROP TABLE infographics_related_infographics_infographics');
        $this->addSql('DROP TABLE infographics_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE infographics_related_posts_post');
        $this->addSql('DROP TABLE infographics_related_press_releases_post');
        $this->addSql('DROP TABLE infographics_related_roads_road');
        $this->addSql('DROP TABLE infographics_related_videos_video');
        $this->addSql('DROP TABLE initiative_related_constructions_construction');
        $this->addSql('DROP TABLE initiative_related_documents_document');
        $this->addSql('DROP TABLE initiative_related_galleries_gallery');
        $this->addSql('DROP TABLE initiative_related_infographics_infographics');
        $this->addSql('DROP TABLE initiative_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE initiative_related_posts_post');
        $this->addSql('DROP TABLE initiative_related_press_releases_post');
        $this->addSql('DROP TABLE initiative_related_roads_road');
        $this->addSql('DROP TABLE initiative_related_videos_video');
        $this->addSql('DROP TABLE post_related_constructions_construction');
        $this->addSql('DROP TABLE post_related_documents_document');
        $this->addSql('DROP TABLE post_related_galleries_gallery');
        $this->addSql('DROP TABLE post_related_infographics_infographics');
        $this->addSql('DROP TABLE post_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE post_related_posts_post');
        $this->addSql('DROP TABLE post_related_press_releases_post');
        $this->addSql('DROP TABLE post_related_roads_road');
        $this->addSql('DROP TABLE post_related_videos_video');
        $this->addSql('DROP TABLE stadium_related_constructions_construction');
        $this->addSql('DROP TABLE stadium_related_documents_document');
        $this->addSql('DROP TABLE stadium_related_galleries_gallery');
        $this->addSql('DROP TABLE stadium_related_infographics_infographics');
        $this->addSql('DROP TABLE stadium_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE stadium_related_posts_post');
        $this->addSql('DROP TABLE stadium_related_press_releases_post');
        $this->addSql('DROP TABLE stadium_related_roads_road');
        $this->addSql('DROP TABLE stadium_related_videos_video');
        $this->addSql('DROP TABLE video_related_constructions_construction');
        $this->addSql('DROP TABLE video_related_documents_document');
        $this->addSql('DROP TABLE video_related_galleries_gallery');
        $this->addSql('DROP TABLE video_related_infographics_infographics');
        $this->addSql('DROP TABLE video_related_metro_stations_metro_station');
        $this->addSql('DROP TABLE video_related_posts_post');
        $this->addSql('DROP TABLE video_related_press_releases_post');
        $this->addSql('DROP TABLE video_related_roads_road');
        $this->addSql('DROP TABLE video_related_videos_video');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE construction_related_constructions_construction (construction_source INT NOT NULL, construction_target INT NOT NULL, INDEX IDX_8A0B8349A6581D40 (construction_source), INDEX IDX_8A0B8349BFBD4DCF (construction_target), PRIMARY KEY(construction_source, construction_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_documents_document (construction_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_C87D3365CF48117A (construction_id), INDEX IDX_C87D3365C33F7837 (document_id), PRIMARY KEY(construction_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_galleries_gallery (construction_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_A548B475CF48117A (construction_id), INDEX IDX_A548B4754E7AF8F (gallery_id), PRIMARY KEY(construction_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_infographics_infographics (construction_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_17D6FB6CF48117A (construction_id), INDEX IDX_17D6FB695A8ED8C (infographics_id), PRIMARY KEY(construction_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_metro_stations_metro_station (construction_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_28DC29B8CF48117A (construction_id), INDEX IDX_28DC29B8F7D58AAA (metro_station_id), PRIMARY KEY(construction_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_posts_post (construction_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_60A9BC3CCF48117A (construction_id), INDEX IDX_60A9BC3C4B89032C (post_id), PRIMARY KEY(construction_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_press_releases_post (construction_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_667D4B57CF48117A (construction_id), INDEX IDX_667D4B574B89032C (post_id), PRIMARY KEY(construction_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_roads_road (construction_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_F2566EA5CF48117A (construction_id), INDEX IDX_F2566EA5962F8178 (road_id), PRIMARY KEY(construction_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE construction_related_videos_video (construction_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_D7BA9532CF48117A (construction_id), INDEX IDX_D7BA953229C1004E (video_id), PRIMARY KEY(construction_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_constructions_construction (document_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_280325C7C33F7837 (document_id), INDEX IDX_280325C7CF48117A (construction_id), PRIMARY KEY(document_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_documents_document (document_source INT NOT NULL, document_target INT NOT NULL, INDEX IDX_F19E7A84E1E8CE15 (document_source), INDEX IDX_F19E7A84F80D9E9A (document_target), PRIMARY KEY(document_source, document_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_galleries_gallery (document_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_45B29796C33F7837 (document_id), INDEX IDX_45B297964E7AF8F (gallery_id), PRIMARY KEY(document_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_infographics_infographics (document_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_6EAA9395C33F7837 (document_id), INDEX IDX_6EAA939595A8ED8C (infographics_id), PRIMARY KEY(document_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_metro_stations_metro_station (document_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_B26938A8C33F7837 (document_id), INDEX IDX_B26938A8F7D58AAA (metro_station_id), PRIMARY KEY(document_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_posts_post (document_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_66C9FA6DC33F7837 (document_id), INDEX IDX_66C9FA6D4B89032C (post_id), PRIMARY KEY(document_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_press_releases_post (document_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_B1497AF0C33F7837 (document_id), INDEX IDX_B1497AF04B89032C (post_id), PRIMARY KEY(document_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_roads_road (document_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_F43628F4C33F7837 (document_id), INDEX IDX_F43628F4962F8178 (road_id), PRIMARY KEY(document_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_related_videos_video (document_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_EBA51BE2C33F7837 (document_id), INDEX IDX_EBA51BE229C1004E (video_id), PRIMARY KEY(document_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_constructions_construction (gallery_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_D9BBF99D4E7AF8F (gallery_id), INDEX IDX_D9BBF99DCF48117A (construction_id), PRIMARY KEY(gallery_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_documents_document (gallery_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_ACA05FE64E7AF8F (gallery_id), INDEX IDX_ACA05FE6C33F7837 (document_id), PRIMARY KEY(gallery_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_galleries_gallery (gallery_source INT NOT NULL, gallery_target INT NOT NULL, INDEX IDX_138CF76CFD0993D1 (gallery_source), INDEX IDX_138CF76CE4ECC35E (gallery_target), PRIMARY KEY(gallery_source, gallery_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_infographics_infographics (gallery_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_2948B444E7AF8F (gallery_id), INDEX IDX_2948B4495A8ED8C (infographics_id), PRIMARY KEY(gallery_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_metro_stations_metro_station (gallery_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_7D58E2314E7AF8F (gallery_id), INDEX IDX_7D58E231F7D58AAA (metro_station_id), PRIMARY KEY(gallery_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_posts_post (gallery_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_14955E0B4E7AF8F (gallery_id), INDEX IDX_14955E0B4B89032C (post_id), PRIMARY KEY(gallery_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_press_releases_post (gallery_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_12A844A14E7AF8F (gallery_id), INDEX IDX_12A844A14B89032C (post_id), PRIMARY KEY(gallery_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_roads_road (gallery_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_866A8C924E7AF8F (gallery_id), INDEX IDX_866A8C92962F8178 (road_id), PRIMARY KEY(gallery_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gallery_related_videos_video (gallery_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_9B9C26E4E7AF8F (gallery_id), INDEX IDX_9B9C26E29C1004E (video_id), PRIMARY KEY(gallery_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_constructions_construction (infographics_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_9F4B70BD95A8ED8C (infographics_id), INDEX IDX_9F4B70BDCF48117A (construction_id), PRIMARY KEY(infographics_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_documents_document (infographics_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_ECBB0B4195A8ED8C (infographics_id), INDEX IDX_ECBB0B41C33F7837 (document_id), PRIMARY KEY(infographics_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_galleries_gallery (infographics_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_D7D3368695A8ED8C (infographics_id), INDEX IDX_D7D336864E7AF8F (gallery_id), PRIMARY KEY(infographics_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_infographics_infographics (infographics_source INT NOT NULL, infographics_target INT NOT NULL, INDEX IDX_9BA3D2EB6C4B9589 (infographics_source), INDEX IDX_9BA3D2EB75AEC506 (infographics_target), PRIMARY KEY(infographics_source, infographics_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_metro_stations_metro_station (infographics_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_7CB8BBE795A8ED8C (infographics_id), INDEX IDX_7CB8BBE7F7D58AAA (metro_station_id), PRIMARY KEY(infographics_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_posts_post (infographics_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_81F6395A95A8ED8C (infographics_id), INDEX IDX_81F6395A4B89032C (post_id), PRIMARY KEY(infographics_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_press_releases_post (infographics_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_5A5A69BE95A8ED8C (infographics_id), INDEX IDX_5A5A69BE4B89032C (post_id), PRIMARY KEY(infographics_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_roads_road (infographics_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_1309EBC395A8ED8C (infographics_id), INDEX IDX_1309EBC3962F8178 (road_id), PRIMARY KEY(infographics_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE infographics_related_videos_video (infographics_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_79CFCFE395A8ED8C (infographics_id), INDEX IDX_79CFCFE329C1004E (video_id), PRIMARY KEY(infographics_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_constructions_construction (initiative_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_3388D7A3AB7D9771 (initiative_id), INDEX IDX_3388D7A3CF48117A (construction_id), PRIMARY KEY(initiative_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_documents_document (initiative_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_BF01A539AB7D9771 (initiative_id), INDEX IDX_BF01A539C33F7837 (document_id), PRIMARY KEY(initiative_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_galleries_gallery (initiative_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_DEEE7E74AB7D9771 (initiative_id), INDEX IDX_DEEE7E744E7AF8F (gallery_id), PRIMARY KEY(initiative_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_infographics_infographics (initiative_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_E4FD8CC0AB7D9771 (initiative_id), INDEX IDX_E4FD8CC095A8ED8C (infographics_id), PRIMARY KEY(initiative_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_metro_stations_metro_station (initiative_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_E04B1EB0AB7D9771 (initiative_id), INDEX IDX_E04B1EB0F7D58AAA (metro_station_id), PRIMARY KEY(initiative_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_posts_post (initiative_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_B73029D9AB7D9771 (initiative_id), INDEX IDX_B73029D94B89032C (post_id), PRIMARY KEY(initiative_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_press_releases_post (initiative_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_4D72A1EAB7D9771 (initiative_id), INDEX IDX_4D72A1E4B89032C (post_id), PRIMARY KEY(initiative_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_roads_road (initiative_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_25CFFB40AB7D9771 (initiative_id), INDEX IDX_25CFFB40962F8178 (road_id), PRIMARY KEY(initiative_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE initiative_related_videos_video (initiative_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_74D622C9AB7D9771 (initiative_id), INDEX IDX_74D622C929C1004E (video_id), PRIMARY KEY(initiative_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_constructions_construction (post_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_F7E7FB254B89032C (post_id), INDEX IDX_F7E7FB25CF48117A (construction_id), PRIMARY KEY(post_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_documents_document (post_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_7FD22EC84B89032C (post_id), INDEX IDX_7FD22EC8C33F7837 (document_id), PRIMARY KEY(post_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_galleries_gallery (post_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_B709220B4B89032C (post_id), INDEX IDX_B709220B4E7AF8F (gallery_id), PRIMARY KEY(post_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_infographics_infographics (post_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_EA9BB2394B89032C (post_id), INDEX IDX_EA9BB23995A8ED8C (infographics_id), PRIMARY KEY(post_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_metro_stations_metro_station (post_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_BF4A89F14B89032C (post_id), INDEX IDX_BF4A89F1F7D58AAA (metro_station_id), PRIMARY KEY(post_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_posts_post (post_source INT NOT NULL, post_target INT NOT NULL, INDEX IDX_289385866FA89B16 (post_source), INDEX IDX_28938586764DCB99 (post_target), PRIMARY KEY(post_source, post_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_press_releases_post (post_source INT NOT NULL, post_target INT NOT NULL, INDEX IDX_CEAD3B1F6FA89B16 (post_source), INDEX IDX_CEAD3B1F764DCB99 (post_target), PRIMARY KEY(post_source, post_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_roads_road (post_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_BA6C571F4B89032C (post_id), INDEX IDX_BA6C571F962F8178 (road_id), PRIMARY KEY(post_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_related_videos_video (post_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_969513324B89032C (post_id), INDEX IDX_9695133229C1004E (video_id), PRIMARY KEY(post_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_constructions_construction (stadium_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_9A3D3C127E860E36 (stadium_id), INDEX IDX_9A3D3C12CF48117A (construction_id), PRIMARY KEY(stadium_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_documents_document (stadium_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_1D8C01747E860E36 (stadium_id), INDEX IDX_1D8C0174C33F7837 (document_id), PRIMARY KEY(stadium_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_galleries_gallery (stadium_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_343B41577E860E36 (stadium_id), INDEX IDX_343B41574E7AF8F (gallery_id), PRIMARY KEY(stadium_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_infographics_infographics (stadium_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_EDB86E2C7E860E36 (stadium_id), INDEX IDX_EDB86E2C95A8ED8C (infographics_id), PRIMARY KEY(stadium_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_metro_stations_metro_station (stadium_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_2A4D130C7E860E36 (stadium_id), INDEX IDX_2A4D130CF7D58AAA (metro_station_id), PRIMARY KEY(stadium_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_posts_post (stadium_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_8ACB99F27E860E36 (stadium_id), INDEX IDX_8ACB99F24B89032C (post_id), PRIMARY KEY(stadium_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_press_releases_post (stadium_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_C189A977E860E36 (stadium_id), INDEX IDX_C189A974B89032C (post_id), PRIMARY KEY(stadium_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_roads_road (stadium_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_18344B6B7E860E36 (stadium_id), INDEX IDX_18344B6B962F8178 (road_id), PRIMARY KEY(stadium_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stadium_related_videos_video (stadium_id INT NOT NULL, video_id INT NOT NULL, INDEX IDX_C9C751D77E860E36 (stadium_id), INDEX IDX_C9C751D729C1004E (video_id), PRIMARY KEY(stadium_id, video_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_constructions_construction (video_id INT NOT NULL, construction_id INT NOT NULL, INDEX IDX_D534D1A929C1004E (video_id), INDEX IDX_D534D1A9CF48117A (construction_id), PRIMARY KEY(video_id, construction_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_documents_document (video_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_FCE6B3A629C1004E (video_id), INDEX IDX_FCE6B3A6C33F7837 (document_id), PRIMARY KEY(video_id, document_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_galleries_gallery (video_id INT NOT NULL, gallery_id INT NOT NULL, INDEX IDX_50118B1C29C1004E (video_id), INDEX IDX_50118B1C4E7AF8F (gallery_id), PRIMARY KEY(video_id, gallery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_infographics_infographics (video_id INT NOT NULL, infographics_id INT NOT NULL, INDEX IDX_3BA7878F29C1004E (video_id), INDEX IDX_3BA7878F95A8ED8C (infographics_id), PRIMARY KEY(video_id, infographics_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_metro_stations_metro_station (video_id INT NOT NULL, metro_station_id INT NOT NULL, INDEX IDX_F3C7B5B329C1004E (video_id), INDEX IDX_F3C7B5B3F7D58AAA (metro_station_id), PRIMARY KEY(video_id, metro_station_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_posts_post (video_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_9B40C1C929C1004E (video_id), INDEX IDX_9B40C1C94B89032C (post_id), PRIMARY KEY(video_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_press_releases_post (video_id INT NOT NULL, post_id INT NOT NULL, INDEX IDX_642443DD29C1004E (video_id), INDEX IDX_642443DD4B89032C (post_id), PRIMARY KEY(video_id, post_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_roads_road (video_id INT NOT NULL, road_id INT NOT NULL, INDEX IDX_9BF135029C1004E (video_id), INDEX IDX_9BF1350962F8178 (road_id), PRIMARY KEY(video_id, road_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE video_related_videos_video (video_source INT NOT NULL, video_target INT NOT NULL, INDEX IDX_90C576A267DDDFBE (video_source), INDEX IDX_90C576A27E388F31 (video_target), PRIMARY KEY(video_source, video_target)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE construction_related_constructions_construction ADD CONSTRAINT FK_8A0B8349A6581D40 FOREIGN KEY (construction_source) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_constructions_construction ADD CONSTRAINT FK_8A0B8349BFBD4DCF FOREIGN KEY (construction_target) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_documents_document ADD CONSTRAINT FK_C87D3365C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_documents_document ADD CONSTRAINT FK_C87D3365CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_galleries_gallery ADD CONSTRAINT FK_A548B4754E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_galleries_gallery ADD CONSTRAINT FK_A548B475CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_infographics_infographics ADD CONSTRAINT FK_17D6FB695A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_infographics_infographics ADD CONSTRAINT FK_17D6FB6CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_metro_stations_metro_station ADD CONSTRAINT FK_28DC29B8CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_metro_stations_metro_station ADD CONSTRAINT FK_28DC29B8F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_posts_post ADD CONSTRAINT FK_60A9BC3C4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_posts_post ADD CONSTRAINT FK_60A9BC3CCF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_press_releases_post ADD CONSTRAINT FK_667D4B574B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_press_releases_post ADD CONSTRAINT FK_667D4B57CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_roads_road ADD CONSTRAINT FK_F2566EA5962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_roads_road ADD CONSTRAINT FK_F2566EA5CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_videos_video ADD CONSTRAINT FK_D7BA953229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE construction_related_videos_video ADD CONSTRAINT FK_D7BA9532CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_constructions_construction ADD CONSTRAINT FK_280325C7C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_constructions_construction ADD CONSTRAINT FK_280325C7CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_documents_document ADD CONSTRAINT FK_F19E7A84E1E8CE15 FOREIGN KEY (document_source) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_documents_document ADD CONSTRAINT FK_F19E7A84F80D9E9A FOREIGN KEY (document_target) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_galleries_gallery ADD CONSTRAINT FK_45B297964E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_galleries_gallery ADD CONSTRAINT FK_45B29796C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_infographics_infographics ADD CONSTRAINT FK_6EAA939595A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_infographics_infographics ADD CONSTRAINT FK_6EAA9395C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_metro_stations_metro_station ADD CONSTRAINT FK_B26938A8C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_metro_stations_metro_station ADD CONSTRAINT FK_B26938A8F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_posts_post ADD CONSTRAINT FK_66C9FA6D4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_posts_post ADD CONSTRAINT FK_66C9FA6DC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_press_releases_post ADD CONSTRAINT FK_B1497AF04B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_press_releases_post ADD CONSTRAINT FK_B1497AF0C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_roads_road ADD CONSTRAINT FK_F43628F4962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_roads_road ADD CONSTRAINT FK_F43628F4C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_videos_video ADD CONSTRAINT FK_EBA51BE229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_related_videos_video ADD CONSTRAINT FK_EBA51BE2C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_constructions_construction ADD CONSTRAINT FK_D9BBF99D4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_constructions_construction ADD CONSTRAINT FK_D9BBF99DCF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_documents_document ADD CONSTRAINT FK_ACA05FE64E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_documents_document ADD CONSTRAINT FK_ACA05FE6C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_galleries_gallery ADD CONSTRAINT FK_138CF76CE4ECC35E FOREIGN KEY (gallery_target) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_galleries_gallery ADD CONSTRAINT FK_138CF76CFD0993D1 FOREIGN KEY (gallery_source) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_infographics_infographics ADD CONSTRAINT FK_2948B444E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_infographics_infographics ADD CONSTRAINT FK_2948B4495A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_metro_stations_metro_station ADD CONSTRAINT FK_7D58E2314E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_metro_stations_metro_station ADD CONSTRAINT FK_7D58E231F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_posts_post ADD CONSTRAINT FK_14955E0B4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_posts_post ADD CONSTRAINT FK_14955E0B4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_press_releases_post ADD CONSTRAINT FK_12A844A14B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_press_releases_post ADD CONSTRAINT FK_12A844A14E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_roads_road ADD CONSTRAINT FK_866A8C924E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_roads_road ADD CONSTRAINT FK_866A8C92962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_videos_video ADD CONSTRAINT FK_9B9C26E29C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gallery_related_videos_video ADD CONSTRAINT FK_9B9C26E4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_constructions_construction ADD CONSTRAINT FK_9F4B70BD95A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_constructions_construction ADD CONSTRAINT FK_9F4B70BDCF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_documents_document ADD CONSTRAINT FK_ECBB0B4195A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_documents_document ADD CONSTRAINT FK_ECBB0B41C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_galleries_gallery ADD CONSTRAINT FK_D7D336864E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_galleries_gallery ADD CONSTRAINT FK_D7D3368695A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_infographics_infographics ADD CONSTRAINT FK_9BA3D2EB6C4B9589 FOREIGN KEY (infographics_source) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_infographics_infographics ADD CONSTRAINT FK_9BA3D2EB75AEC506 FOREIGN KEY (infographics_target) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_metro_stations_metro_station ADD CONSTRAINT FK_7CB8BBE795A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_metro_stations_metro_station ADD CONSTRAINT FK_7CB8BBE7F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_posts_post ADD CONSTRAINT FK_81F6395A4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_posts_post ADD CONSTRAINT FK_81F6395A95A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_press_releases_post ADD CONSTRAINT FK_5A5A69BE4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_press_releases_post ADD CONSTRAINT FK_5A5A69BE95A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_roads_road ADD CONSTRAINT FK_1309EBC395A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_roads_road ADD CONSTRAINT FK_1309EBC3962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_videos_video ADD CONSTRAINT FK_79CFCFE329C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE infographics_related_videos_video ADD CONSTRAINT FK_79CFCFE395A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_constructions_construction ADD CONSTRAINT FK_3388D7A3AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_constructions_construction ADD CONSTRAINT FK_3388D7A3CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_documents_document ADD CONSTRAINT FK_BF01A539AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_documents_document ADD CONSTRAINT FK_BF01A539C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_galleries_gallery ADD CONSTRAINT FK_DEEE7E744E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_galleries_gallery ADD CONSTRAINT FK_DEEE7E74AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_infographics_infographics ADD CONSTRAINT FK_E4FD8CC095A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_infographics_infographics ADD CONSTRAINT FK_E4FD8CC0AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_metro_stations_metro_station ADD CONSTRAINT FK_E04B1EB0AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_metro_stations_metro_station ADD CONSTRAINT FK_E04B1EB0F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_posts_post ADD CONSTRAINT FK_B73029D94B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_posts_post ADD CONSTRAINT FK_B73029D9AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_press_releases_post ADD CONSTRAINT FK_4D72A1E4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_press_releases_post ADD CONSTRAINT FK_4D72A1EAB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_roads_road ADD CONSTRAINT FK_25CFFB40962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_roads_road ADD CONSTRAINT FK_25CFFB40AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_videos_video ADD CONSTRAINT FK_74D622C929C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE initiative_related_videos_video ADD CONSTRAINT FK_74D622C9AB7D9771 FOREIGN KEY (initiative_id) REFERENCES initiative (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_constructions_construction ADD CONSTRAINT FK_F7E7FB254B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_constructions_construction ADD CONSTRAINT FK_F7E7FB25CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_documents_document ADD CONSTRAINT FK_7FD22EC84B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_documents_document ADD CONSTRAINT FK_7FD22EC8C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_galleries_gallery ADD CONSTRAINT FK_B709220B4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_galleries_gallery ADD CONSTRAINT FK_B709220B4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_infographics_infographics ADD CONSTRAINT FK_EA9BB2394B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_infographics_infographics ADD CONSTRAINT FK_EA9BB23995A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_metro_stations_metro_station ADD CONSTRAINT FK_BF4A89F14B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_metro_stations_metro_station ADD CONSTRAINT FK_BF4A89F1F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_posts_post ADD CONSTRAINT FK_289385866FA89B16 FOREIGN KEY (post_source) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_posts_post ADD CONSTRAINT FK_28938586764DCB99 FOREIGN KEY (post_target) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_press_releases_post ADD CONSTRAINT FK_CEAD3B1F6FA89B16 FOREIGN KEY (post_source) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_press_releases_post ADD CONSTRAINT FK_CEAD3B1F764DCB99 FOREIGN KEY (post_target) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_roads_road ADD CONSTRAINT FK_BA6C571F4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_roads_road ADD CONSTRAINT FK_BA6C571F962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_videos_video ADD CONSTRAINT FK_9695133229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_related_videos_video ADD CONSTRAINT FK_969513324B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_constructions_construction ADD CONSTRAINT FK_9A3D3C127E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_constructions_construction ADD CONSTRAINT FK_9A3D3C12CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_documents_document ADD CONSTRAINT FK_1D8C01747E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_documents_document ADD CONSTRAINT FK_1D8C0174C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_galleries_gallery ADD CONSTRAINT FK_343B41574E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_galleries_gallery ADD CONSTRAINT FK_343B41577E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_infographics_infographics ADD CONSTRAINT FK_EDB86E2C7E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_infographics_infographics ADD CONSTRAINT FK_EDB86E2C95A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_metro_stations_metro_station ADD CONSTRAINT FK_2A4D130C7E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_metro_stations_metro_station ADD CONSTRAINT FK_2A4D130CF7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_posts_post ADD CONSTRAINT FK_8ACB99F24B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_posts_post ADD CONSTRAINT FK_8ACB99F27E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_press_releases_post ADD CONSTRAINT FK_C189A974B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_press_releases_post ADD CONSTRAINT FK_C189A977E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_roads_road ADD CONSTRAINT FK_18344B6B7E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_roads_road ADD CONSTRAINT FK_18344B6B962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_videos_video ADD CONSTRAINT FK_C9C751D729C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stadium_related_videos_video ADD CONSTRAINT FK_C9C751D77E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_constructions_construction ADD CONSTRAINT FK_D534D1A929C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_constructions_construction ADD CONSTRAINT FK_D534D1A9CF48117A FOREIGN KEY (construction_id) REFERENCES construction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_documents_document ADD CONSTRAINT FK_FCE6B3A629C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_documents_document ADD CONSTRAINT FK_FCE6B3A6C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_galleries_gallery ADD CONSTRAINT FK_50118B1C29C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_galleries_gallery ADD CONSTRAINT FK_50118B1C4E7AF8F FOREIGN KEY (gallery_id) REFERENCES gallery (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_infographics_infographics ADD CONSTRAINT FK_3BA7878F29C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_infographics_infographics ADD CONSTRAINT FK_3BA7878F95A8ED8C FOREIGN KEY (infographics_id) REFERENCES infographics (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_metro_stations_metro_station ADD CONSTRAINT FK_F3C7B5B329C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_metro_stations_metro_station ADD CONSTRAINT FK_F3C7B5B3F7D58AAA FOREIGN KEY (metro_station_id) REFERENCES metro_station (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_posts_post ADD CONSTRAINT FK_9B40C1C929C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_posts_post ADD CONSTRAINT FK_9B40C1C94B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_press_releases_post ADD CONSTRAINT FK_642443DD29C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_press_releases_post ADD CONSTRAINT FK_642443DD4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_roads_road ADD CONSTRAINT FK_9BF135029C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_roads_road ADD CONSTRAINT FK_9BF1350962F8178 FOREIGN KEY (road_id) REFERENCES road (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_videos_video ADD CONSTRAINT FK_90C576A267DDDFBE FOREIGN KEY (video_source) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE video_related_videos_video ADD CONSTRAINT FK_90C576A27E388F31 FOREIGN KEY (video_target) REFERENCES video (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE related_i_document_posts_post_documents');
        $this->addSql('DROP TABLE related_i_document_infographics_infographics_documents');
        $this->addSql('DROP TABLE related_i_document_galleries_gallery_documents');
        $this->addSql('DROP TABLE related_i_document_videos_video_documents');
        $this->addSql('DROP TABLE related_document_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_document_roads_road');
        $this->addSql('DROP TABLE related_document_documents_document');
        $this->addSql('DROP TABLE related_stadium_posts_post');
        $this->addSql('DROP TABLE related_stadium_infographics_infographics');
        $this->addSql('DROP TABLE related_stadium_galleries_gallery');
        $this->addSql('DROP TABLE related_stadium_videos_video');
        $this->addSql('DROP TABLE related_stadium_constructions_construction');
        $this->addSql('DROP TABLE related_stadium_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_stadium_roads_road');
        $this->addSql('DROP TABLE related_stadium_documents_document');
        $this->addSql('DROP TABLE related_i_gallery_posts_post_galleries');
        $this->addSql('DROP TABLE related_i_gallery_infographics_infographics_galleries');
        $this->addSql('DROP TABLE related_gallery_galleries_gallery');
        $this->addSql('DROP TABLE related_i_gallery_videos_video_galleries');
        $this->addSql('DROP TABLE related_gallery_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_gallery_roads_road');
        $this->addSql('DROP TABLE related_i_construction_posts_post_constructions');
        $this->addSql('DROP TABLE related_i_construction_infographics_infographics_constructions');
        $this->addSql('DROP TABLE related_i_construction_galleries_gallery_constructions');
        $this->addSql('DROP TABLE related_i_construction_videos_video_constructions');
        $this->addSql('DROP TABLE related_construction_constructions_construction');
        $this->addSql('DROP TABLE related_construction_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_construction_roads_road');
        $this->addSql('DROP TABLE related_i_construction_documents_document_constructions');
        $this->addSql('DROP TABLE related_post_posts_post');
        $this->addSql('DROP TABLE related_i_post_videos_video_posts');
        $this->addSql('DROP TABLE related_post_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_post_roads_road');
        $this->addSql('DROP TABLE related_video_videos_video');
        $this->addSql('DROP TABLE related_video_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_video_roads_road');
        $this->addSql('DROP TABLE related_i_infographics_posts_post_infographics');
        $this->addSql('DROP TABLE related_infographics_infographics_infographics');
        $this->addSql('DROP TABLE related_i_infographics_videos_video_infographics');
        $this->addSql('DROP TABLE related_infographics_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_infographics_roads_road');
        $this->addSql('DROP TABLE related_initiative_posts_post');
        $this->addSql('DROP TABLE related_initiative_infographics_infographics');
        $this->addSql('DROP TABLE related_initiative_galleries_gallery');
        $this->addSql('DROP TABLE related_initiative_videos_video');
        $this->addSql('DROP TABLE related_initiative_constructions_construction');
        $this->addSql('DROP TABLE related_initiative_metro_stations_metro_station');
        $this->addSql('DROP TABLE related_initiative_roads_road');
        $this->addSql('DROP TABLE related_initiative_documents_document');
    }
}
