<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20200719155401 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $this->abortIf(
            $this->connection->getDatabasePlatform()->getName() != 'mysql',
            'Migration can only be executed safely on \'mysql\'.'
        );
        $roles = [
            0 => "ROLE_ADMIN_POST_EDIT",
            1 => "ROLE_ADMIN_POST_LIST",
            2 => "ROLE_ADMIN_POST_CREATE",
            3 => "ROLE_ADMIN_POST_VIEW",
            4 => "ROLE_ADMIN_CATEGORY_LIST",
            5 => "ROLE_ADMIN_CATEGORY_VIEW",
            6 => "ROLE_ADMIN_ARTICLE_RUBRICS_LIST",
            7 => "ROLE_ADMIN_ARTICLE_RUBRICS_VIEW",
            8 => "ROLE_ADMIN_AUTHOR_EDIT",
            9 => "ROLE_ADMIN_AUTHOR_LIST",
            10 => "ROLE_ADMIN_AUTHOR_CREATE",
            11 => "ROLE_ADMIN_AUTHOR_VIEW",
            12 => "ROLE_ADMIN_ARTICLE_SOURCE_LIST",
            13 => "ROLE_ADMIN_ARTICLE_SOURCE_VIEW",
            14 => "ROLE_AMG_PAGE_ADMIN_PAGE_EDIT",
            15 => "ROLE_AMG_PAGE_ADMIN_PAGE_LIST",
            16 => "ROLE_AMG_PAGE_ADMIN_PAGE_CREATE",
            17 => "ROLE_AMG_PAGE_ADMIN_PAGE_VIEW",
            18 => "ROLE_AMG_TAG_ADMIN_TAG_LIST",
            19 => "ROLE_AMG_TAG_ADMIN_TAG_VIEW",
            20 => "ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_EDIT",
            21 => "ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_LIST",
            22 => "ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_CREATE",
            23 => "ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_VIEW",
            24 => "ROLE_ADMIN_GALLERY_EDIT",
            25 => "ROLE_ADMIN_GALLERY_LIST",
            26 => "ROLE_ADMIN_GALLERY_CREATE",
            27 => "ROLE_ADMIN_GALLERY_VIEW",
            28 => "ROLE_ADMIN_GALLERY_MEDIA_EDIT",
            29 => "ROLE_ADMIN_GALLERY_MEDIA_LIST",
            30 => "ROLE_ADMIN_GALLERY_MEDIA_CREATE",
            31 => "ROLE_ADMIN_GALLERY_MEDIA_VIEW",
            32 => "ROLE_ADMIN_POST_ATTACHMENT_EDIT",
            33 => "ROLE_ADMIN_POST_ATTACHMENT_LIST",
            34 => "ROLE_ADMIN_POST_ATTACHMENT_CREATE",
            35 => "ROLE_ADMIN_POST_ATTACHMENT_VIEW",
            36 => "ROLE_ADMIN_VIDEO_EDIT",
            37 => "ROLE_ADMIN_VIDEO_LIST",
            38 => "ROLE_ADMIN_VIDEO_CREATE",
            39 => "ROLE_ADMIN_VIDEO_VIEW",
            40 => "ROLE_ADMIN_INFOGRAPHICS_EDIT",
            41 => "ROLE_ADMIN_INFOGRAPHICS_LIST",
            42 => "ROLE_ADMIN_INFOGRAPHICS_CREATE",
            43 => "ROLE_ADMIN_INFOGRAPHICS_VIEW",
            44 => "ROLE_ADMIN_DOCUMENT_LIST",
            45 => "ROLE_ADMIN_DOCUMENT_VIEW",
            46 => "ROLE_ADMIN_DECISION_DOCUMENT_LIST",
            47 => "ROLE_ADMIN_DECISION_DOCUMENT_VIEW",
            48 => "ROLE_ADMIN_LAW_DOCUMENT_LIST",
            49 => "ROLE_ADMIN_LAW_DOCUMENT_VIEW",
            50 => "ROLE_ADMIN_DRAFT_DOCUMENT_LIST",
            51 => "ROLE_ADMIN_DRAFT_DOCUMENT_VIEW",
            52 => "ROLE_ADMIN_DOCUMENT_HAS_MEDIA_LIST",
            53 => "ROLE_ADMIN_DOCUMENT_HAS_MEDIA_VIEW",
            54 => "ROLE_ADMIN_OUTGOING_AGENCY_LIST",
            55 => "ROLE_ADMIN_OUTGOING_AGENCY_VIEW",
            56 => "ROLE_ADMIN_DOCUMENT_RUBRIC_LIST",
            57 => "ROLE_ADMIN_DOCUMENT_RUBRIC_VIEW",
            58 => "ROLE_ADMIN_PERSON_LIST",
            59 => "ROLE_ADMIN_PERSON_VIEW",
            60 => "ROLE_ADMIN_ORGANIZATION_DIRECTORY_LIST",
            61 => "ROLE_ADMIN_ORGANIZATION_DIRECTORY_VIEW",
            62 => "ROLE_ADMIN_CONTACT_PERSON_LIST",
            63 => "ROLE_ADMIN_CONTACT_PERSON_VIEW",
            64 => "ROLE_ADMIN_ORGANIZATION_LIST",
            65 => "ROLE_ADMIN_ORGANIZATION_VIEW",
            66 => "ROLE_ADMIN_MEDIA_CATEGORY_LIST",
            67 => "ROLE_ADMIN_MEDIA_CATEGORY_VIEW",
            68 => "ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST",
            69 => "ROLE_SONATA_MEDIA_ADMIN_MEDIA_VIEW",
            70 => "ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_LIST",
            71 => "ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_VIEW",
            72 => "ROLE_AMG_PAGE_ADMIN_BLOCK_EDIT",
            73 => "ROLE_AMG_PAGE_ADMIN_BLOCK_LIST",
            74 => "ROLE_AMG_PAGE_ADMIN_BLOCK_CREATE",
            75 => "ROLE_AMG_PAGE_ADMIN_BLOCK_VIEW",
            76 => "ROLE_AMG_PAGE_ADMIN_BLOCK_MASTER",
            77 => "ROLE_USER",
            78 => "ROLE_SONATA_ADMIN",
        ];

        $serializedRoles = serialize($roles);

        $this->addSql("UPDATE fos_user_group SET roles = '$serializedRoles' WHERE id = 14");
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        $this->abortIf(
            $this->connection->getDatabasePlatform()->getName() != 'mysql',
            'Migration can only be executed safely on \'mysql\'.'
        );

        $serializedRoles = 'a:83:{i:0;s:20:"ROLE_ADMIN_POST_EDIT";i:1;s:20:"ROLE_ADMIN_POST_LIST";i:2;s:22:"ROLE_ADMIN_POST_CREATE";i:3;s:20:"ROLE_ADMIN_POST_VIEW";i:4;s:22:"ROLE_ADMIN_AUTHOR_EDIT";i:5;s:22:"ROLE_ADMIN_AUTHOR_LIST";i:6;s:24:"ROLE_ADMIN_AUTHOR_CREATE";i:7;s:22:"ROLE_ADMIN_AUTHOR_VIEW";i:8;s:29:"ROLE_AMG_PAGE_ADMIN_PAGE_EDIT";i:9;s:29:"ROLE_AMG_PAGE_ADMIN_PAGE_LIST";i:10;s:31:"ROLE_AMG_PAGE_ADMIN_PAGE_CREATE";i:11;s:29:"ROLE_AMG_PAGE_ADMIN_PAGE_VIEW";i:12;s:38:"ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_EDIT";i:13;s:38:"ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_LIST";i:14;s:40:"ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_CREATE";i:15;s:38:"ROLE_ADMIN_EMBEDDED_CONTENT_QUOTE_VIEW";i:16;s:23:"ROLE_ADMIN_GALLERY_LIST";i:17;s:23:"ROLE_ADMIN_GALLERY_VIEW";i:18;s:29:"ROLE_ADMIN_GALLERY_MEDIA_LIST";i:19;s:29:"ROLE_ADMIN_GALLERY_MEDIA_VIEW";i:20;s:31:"ROLE_ADMIN_POST_ATTACHMENT_EDIT";i:21;s:31:"ROLE_ADMIN_POST_ATTACHMENT_LIST";i:22;s:33:"ROLE_ADMIN_POST_ATTACHMENT_CREATE";i:23;s:31:"ROLE_ADMIN_POST_ATTACHMENT_VIEW";i:24;s:21:"ROLE_ADMIN_VIDEO_LIST";i:25;s:21:"ROLE_ADMIN_VIDEO_VIEW";i:26;s:28:"ROLE_ADMIN_INFOGRAPHICS_LIST";i:27;s:28:"ROLE_ADMIN_INFOGRAPHICS_VIEW";i:28;s:24:"ROLE_ADMIN_DOCUMENT_LIST";i:29;s:24:"ROLE_ADMIN_DOCUMENT_VIEW";i:30;s:33:"ROLE_ADMIN_DECISION_DOCUMENT_LIST";i:31;s:33:"ROLE_ADMIN_DECISION_DOCUMENT_VIEW";i:32;s:28:"ROLE_ADMIN_LAW_DOCUMENT_LIST";i:33;s:28:"ROLE_ADMIN_LAW_DOCUMENT_VIEW";i:34;s:30:"ROLE_ADMIN_DRAFT_DOCUMENT_LIST";i:35;s:30:"ROLE_ADMIN_DRAFT_DOCUMENT_VIEW";i:36;s:34:"ROLE_ADMIN_DOCUMENT_HAS_MEDIA_LIST";i:37;s:34:"ROLE_ADMIN_DOCUMENT_HAS_MEDIA_VIEW";i:38;s:31:"ROLE_ADMIN_OUTGOING_AGENCY_LIST";i:39;s:31:"ROLE_ADMIN_OUTGOING_AGENCY_VIEW";i:40;s:31:"ROLE_ADMIN_DOCUMENT_RUBRIC_LIST";i:41;s:31:"ROLE_ADMIN_DOCUMENT_RUBRIC_VIEW";i:42;s:22:"ROLE_ADMIN_PERSON_LIST";i:43;s:22:"ROLE_ADMIN_PERSON_VIEW";i:44;s:38:"ROLE_ADMIN_ORGANIZATION_DIRECTORY_LIST";i:45;s:38:"ROLE_ADMIN_ORGANIZATION_DIRECTORY_VIEW";i:46;s:30:"ROLE_ADMIN_CONTACT_PERSON_LIST";i:47;s:30:"ROLE_ADMIN_CONTACT_PERSON_VIEW";i:48;s:28:"ROLE_ADMIN_ORGANIZATION_LIST";i:49;s:28:"ROLE_ADMIN_ORGANIZATION_VIEW";i:50;s:30:"ROLE_ADMIN_MEDIA_CATEGORY_LIST";i:51;s:30:"ROLE_ADMIN_MEDIA_CATEGORY_VIEW";i:52;s:34:"ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDIT";i:53;s:34:"ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST";i:54;s:36:"ROLE_SONATA_MEDIA_ADMIN_MEDIA_CREATE";i:55;s:34:"ROLE_SONATA_MEDIA_ADMIN_MEDIA_VIEW";i:56;s:46:"ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_EDIT";i:57;s:46:"ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_LIST";i:58;s:48:"ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_CREATE";i:59;s:46:"ROLE_SONATA_MEDIA_ADMIN_GALLERY_HAS_MEDIA_VIEW";i:60;s:9:"ROLE_USER";i:61;s:17:"ROLE_SONATA_ADMIN";i:62;s:30:"ROLE_AMG_PAGE_ADMIN_BLOCK_EDIT";i:63;s:30:"ROLE_AMG_PAGE_ADMIN_BLOCK_LIST";i:64;s:32:"ROLE_AMG_PAGE_ADMIN_BLOCK_CREATE";i:65;s:30:"ROLE_AMG_PAGE_ADMIN_BLOCK_VIEW";i:66;s:24:"ROLE_ADMIN_CATEGORY_LIST";i:67;s:24:"ROLE_ADMIN_CATEGORY_VIEW";i:68;s:31:"ROLE_ADMIN_ARTICLE_RUBRICS_LIST";i:69;s:31:"ROLE_ADMIN_ARTICLE_RUBRICS_VIEW";i:70;s:30:"ROLE_ADMIN_ARTICLE_SOURCE_LIST";i:71;s:30:"ROLE_ADMIN_ARTICLE_SOURCE_VIEW";i:72;s:27:"ROLE_AMG_TAG_ADMIN_TAG_LIST";i:73;s:27:"ROLE_AMG_TAG_ADMIN_TAG_VIEW";i:74;s:23:"ROLE_ADMIN_GALLERY_EDIT";i:75;s:25:"ROLE_ADMIN_GALLERY_CREATE";i:76;s:29:"ROLE_ADMIN_GALLERY_MEDIA_EDIT";i:77;s:31:"ROLE_ADMIN_GALLERY_MEDIA_CREATE";i:78;s:21:"ROLE_ADMIN_VIDEO_EDIT";i:79;s:23:"ROLE_ADMIN_VIDEO_CREATE";i:80;s:28:"ROLE_ADMIN_INFOGRAPHICS_EDIT";i:81;s:30:"ROLE_ADMIN_INFOGRAPHICS_CREATE";i:82;s:32:"ROLE_AMG_PAGE_ADMIN_BLOCK_MASTER";}';

        $this->addSql("UPDATE fos_user_group SET roles = '$serializedRoles' WHERE id = 14");
    }
}
