<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MetroStation extends \AppBundle\Entity\MetroStation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'line', 'medias', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'entranceHallDescription', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'featureDescription', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'capacityDescription', 'relatedGalleries', 'id', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionStatus', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionStatusDescription', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionStartYear', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionEndYear', 'distance', 'title', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'administrativeUnit', 'image', 'teaser', 'content', 'publishable', 'currently', 'video', 'panorama', 'createdAt', 'updatedAt', 'mobileContent', 'x', 'y', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'extraInformation');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'line', 'medias', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'entranceHallDescription', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'featureDescription', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'capacityDescription', 'relatedGalleries', 'id', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionStatus', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionStatusDescription', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionStartYear', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'constructionEndYear', 'distance', 'title', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'administrativeUnit', 'image', 'teaser', 'content', 'publishable', 'currently', 'video', 'panorama', 'createdAt', 'updatedAt', 'mobileContent', 'x', 'y', '' . "\0" . 'AppBundle\\Entity\\MetroStation' . "\0" . 'extraInformation');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MetroStation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine', array());

        return parent::getLine();
    }

    /**
     * {@inheritDoc}
     */
    public function setLine($line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine', array($line));

        return parent::setLine($line);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', array());

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedias($images)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedias', array($images));

        return parent::setMedias($images);
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\AppBundle\Entity\MetroStationImage $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', array($media));

        return parent::addMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntranceHallDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntranceHallDescription', array());

        return parent::getEntranceHallDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntranceHallDescription($entranceHallDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntranceHallDescription', array($entranceHallDescription));

        return parent::setEntranceHallDescription($entranceHallDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatureDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatureDescription', array());

        return parent::getFeatureDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatureDescription($featureDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatureDescription', array($featureDescription));

        return parent::setFeatureDescription($featureDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacityDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacityDescription', array());

        return parent::getCapacityDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacityDescription($capacityDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacityDescription', array($capacityDescription));

        return parent::setCapacityDescription($capacityDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getFunctionalPurpose()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFunctionalPurpose', array());

        return parent::getFunctionalPurpose();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionStatusTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionStatusTranslations', array());

        return parent::getConstructionStatusTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function getSearchData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchData', array());

        return parent::getSearchData();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescription', array());

        return parent::getMetaDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaKeywords', array());

        return parent::getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionFunctional()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionFunctional', array());

        return parent::getConstructionFunctional();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedGalleries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedGalleries', array());

        return parent::getRelatedGalleries();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedGalleries($relatedGalleries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedGalleries', array($relatedGalleries));

        return parent::setRelatedGalleries($relatedGalleries);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistance', array());

        return parent::getDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistance($distance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistance', array($distance));

        return parent::setDistance($distance);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionStatus', array());

        return parent::getConstructionStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstructionStatus($constructionStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstructionStatus', array($constructionStatus));

        return parent::setConstructionStatus($constructionStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionStatusDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionStatusDescription', array());

        return parent::getConstructionStatusDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstructionStatusDescription($constructionStatusDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstructionStatusDescription', array($constructionStatusDescription));

        return parent::setConstructionStatusDescription($constructionStatusDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionStartYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionStartYear', array());

        return parent::getConstructionStartYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstructionStartYear($constructionStartYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstructionStartYear', array($constructionStartYear));

        return parent::setConstructionStartYear($constructionStartYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionEndYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionEndYear', array());

        return parent::getConstructionEndYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstructionEndYear($constructionEndYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstructionEndYear', array($constructionEndYear));

        return parent::setConstructionEndYear($constructionEndYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressText', array());

        return parent::getAddressText();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoPointCoordinatesInGeoJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoPointCoordinatesInGeoJson', array());

        return parent::getGeoPointCoordinatesInGeoJson();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoPointAsLonLatArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoPointAsLonLatArray', array());

        return parent::getGeoPointAsLonLatArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectName', array());

        return parent::getObjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoordinates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoordinates', array());

        return parent::getCoordinates();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityReference', array());

        return parent::getEntityReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(\AppBundle\Entity\Embeddable\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeUnit', array());

        return parent::getAdministrativeUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeUnit($administrativeUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeUnit', array($administrativeUnit));

        return parent::setAdministrativeUnit($administrativeUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeArea', array());

        return parent::getAdministrativeArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getCityDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityDistrict', array());

        return parent::getCityDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\Application\Sonata\MediaBundle\Entity\Media $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeaser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeaser', array());

        return parent::getTeaser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeaser($teaser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeaser', array($teaser));

        return parent::setTeaser($teaser);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', array());

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', array($content));

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishable($publishable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishable', array($publishable));

        return parent::setPublishable($publishable);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublishable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublishable', array());

        return parent::isPublishable();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrently()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrently', array());

        return parent::getCurrently();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrently($currently)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrently', array($currently));

        return parent::setCurrently($currently);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', array());

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo(\Application\Sonata\MediaBundle\Entity\Media $video = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', array($video));

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanorama()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanorama', array());

        return parent::getPanorama();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanorama($panorama)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanorama', array($panorama));

        return parent::setPanorama($panorama);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileContent', array());

        return parent::getMobileContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileContent($mobileContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileContent', array($mobileContent));

        return parent::setMobileContent($mobileContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX', array());

        return parent::getX();
    }

    /**
     * {@inheritDoc}
     */
    public function setX($x)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX', array($x));

        return parent::setX($x);
    }

    /**
     * {@inheritDoc}
     */
    public function getY()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getY', array());

        return parent::getY();
    }

    /**
     * {@inheritDoc}
     */
    public function setY($y)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setY', array($y));

        return parent::setY($y);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraInformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraInformation', array());

        return parent::getExtraInformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraInformation($extraInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraInformation', array($extraInformation));

        return parent::setExtraInformation($extraInformation);
    }

}
