<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Destruction extends \AppBundle\Entity\Destruction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'series', 'destructionYear', 'destructionQuarter', 'destructed', 'id', '' . "\0" . 'AppBundle\\Entity\\Destruction' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Destruction' . "\0" . 'administrativeUnit');
        }

        return array('__isInitialized__', 'series', 'destructionYear', 'destructionQuarter', 'destructed', 'id', '' . "\0" . 'AppBundle\\Entity\\Destruction' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Destruction' . "\0" . 'administrativeUnit');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Destruction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSeries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeries', array());

        return parent::getSeries();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeries($series)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeries', array($series));

        return parent::setSeries($series);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestructionYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestructionYear', array());

        return parent::getDestructionYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestructionYear($destructionYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestructionYear', array($destructionYear));

        return parent::setDestructionYear($destructionYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestructionQuarter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestructionQuarter', array());

        return parent::getDestructionQuarter();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestructionQuarter($destructionQuarter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestructionQuarter', array($destructionQuarter));

        return parent::setDestructionQuarter($destructionQuarter);
    }

    /**
     * {@inheritDoc}
     */
    public function isDestructed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDestructed', array());

        return parent::isDestructed();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestructed($destructed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestructed', array($destructed));

        return parent::setDestructed($destructed);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(\AppBundle\Entity\Embeddable\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeUnit', array());

        return parent::getAdministrativeUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeUnit($administrativeUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeUnit', array($administrativeUnit));

        return parent::setAdministrativeUnit($administrativeUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeArea', array());

        return parent::getAdministrativeArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getCityDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityDistrict', array());

        return parent::getCityDistrict();
    }

}
