<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \AppBundle\Entity\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'id', 'rubrics', 'popularised', 'forRss', 'forYaZenRss', 'wordIsSmallRss', 'inTop', 'inTopOrder', 'views', 'slug', 'publishDate', 'publishTime', 'journalistWriter', 'editor', 'administrativeAreas', 'cityDistricts', 'wordIsSmallContent', 'deletedAt', 'title', 'teaser', 'lead', 'content', 'metaDescription', 'metaKeywords', 'image', 'heroImage', 'author', 'source', 'attachments', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'category', 'relatedPosts', 'relatedInfographics', 'relatedGalleries', 'relatedVideos', 'relatedConstructions', 'relatedMetroStations', 'relatedRoads', 'relatedDocuments', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'tags', 'publishable', 'publishStartDate', 'publishEndDate', 'feedable', 'publishableInRss', 'searchable', 'relevantNewsShown', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'administrativeUnit', 'createdAt', 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'isCommentsOpen', 'createdBy', 'updatedBy', 'deletedBy', 'priorityPosition', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'entityLock', 'owners', 'mobileContent');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'id', 'rubrics', 'popularised', 'forRss', 'forYaZenRss', 'wordIsSmallRss', 'inTop', 'inTopOrder', 'views', 'slug', 'publishDate', 'publishTime', 'journalistWriter', 'editor', 'administrativeAreas', 'cityDistricts', 'wordIsSmallContent', 'deletedAt', 'title', 'teaser', 'lead', 'content', 'metaDescription', 'metaKeywords', 'image', 'heroImage', 'author', 'source', 'attachments', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'category', 'relatedPosts', 'relatedInfographics', 'relatedGalleries', 'relatedVideos', 'relatedConstructions', 'relatedMetroStations', 'relatedRoads', 'relatedDocuments', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'tags', 'publishable', 'publishStartDate', 'publishEndDate', 'feedable', 'publishableInRss', 'searchable', 'relevantNewsShown', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'administrativeUnit', 'createdAt', 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'isCommentsOpen', 'createdBy', 'updatedBy', 'deletedBy', 'priorityPosition', '' . "\0" . 'AppBundle\\Entity\\Post' . "\0" . 'entityLock', 'owners', 'mobileContent');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRubrics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRubrics', array());

        return parent::getRubrics();
    }

    /**
     * {@inheritDoc}
     */
    public function setRubrics($rubrics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRubrics', array($rubrics));

        return parent::setRubrics($rubrics);
    }

    /**
     * {@inheritDoc}
     */
    public function addRubric(\AppBundle\Entity\Rubric $rubric)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRubric', array($rubric));

        return parent::addRubric($rubric);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function isPopularised()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPopularised', array());

        return parent::isPopularised();
    }

    /**
     * {@inheritDoc}
     */
    public function setPopularised($popularised)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPopularised', array($popularised));

        return parent::setPopularised($popularised);
    }

    /**
     * {@inheritDoc}
     */
    public function isForRss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isForRss', array());

        return parent::isForRss();
    }

    /**
     * {@inheritDoc}
     */
    public function setForRss($forRss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForRss', array($forRss));

        return parent::setForRss($forRss);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishDate', array());

        return parent::getPublishDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishDate($publishDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishDate', array($publishDate));

        return parent::setPublishDate($publishDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishTime', array());

        return parent::getPublishTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishTime($publishTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishTime', array($publishTime));

        return parent::setPublishTime($publishTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressText', array());

        return parent::getAddressText();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishStartDate(\DateTime $publishStartDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishStartDate', array($publishStartDate));

        return parent::setPublishStartDate($publishStartDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllRelatedConstruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllRelatedConstruction', array());

        return parent::getAllRelatedConstruction();
    }

    /**
     * {@inheritDoc}
     */
    public function isInTop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInTop', array());

        return parent::isInTop();
    }

    /**
     * {@inheritDoc}
     */
    public function setInTop($inTop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInTop', array($inTop));

        return parent::setInTop($inTop);
    }

    /**
     * {@inheritDoc}
     */
    public function isForYaZenRss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isForYaZenRss', array());

        return parent::isForYaZenRss();
    }

    /**
     * {@inheritDoc}
     */
    public function setForYaZenRss($forYaZenRss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForYaZenRss', array($forYaZenRss));

        return parent::setForYaZenRss($forYaZenRss);
    }

    /**
     * {@inheritDoc}
     */
    public function isSubordinatePublication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSubordinatePublication', array());

        return parent::isSubordinatePublication();
    }

    /**
     * {@inheritDoc}
     */
    public function getJournalistWriter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJournalistWriter', array());

        return parent::getJournalistWriter();
    }

    /**
     * {@inheritDoc}
     */
    public function setJournalistWriter($journalistWriter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJournalistWriter', array($journalistWriter));

        return parent::setJournalistWriter($journalistWriter);
    }

    /**
     * {@inheritDoc}
     */
    public function getCityDistricts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityDistricts', array());

        return parent::getCityDistricts();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeAreas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeAreas', array());

        return parent::getAdministrativeAreas();
    }

    /**
     * {@inheritDoc}
     */
    public function setCityDistricts($cityDistricts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCityDistricts', array($cityDistricts));

        return parent::setCityDistricts($cityDistricts);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeAreas($administrativeAreas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeAreas', array($administrativeAreas));

        return parent::setAdministrativeAreas($administrativeAreas);
    }

    /**
     * {@inheritDoc}
     */
    public function isWordIsSmallRss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isWordIsSmallRss', array());

        return parent::isWordIsSmallRss();
    }

    /**
     * {@inheritDoc}
     */
    public function setWordIsSmallRss($wordIsSmallRss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWordIsSmallRss', array($wordIsSmallRss));

        return parent::setWordIsSmallRss($wordIsSmallRss);
    }

    /**
     * {@inheritDoc}
     */
    public function setWordIsSmallContent($wordIsSmallContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWordIsSmallContent', array($wordIsSmallContent));

        return parent::setWordIsSmallContent($wordIsSmallContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getWordIsSmallContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWordIsSmallContent', array());

        return parent::getWordIsSmallContent();
    }

    /**
     * {@inheritDoc}
     */
    public function getEditor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditor', array());

        return parent::getEditor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditor($editor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditor', array($editor));

        return parent::setEditor($editor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', array());

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', array($deletedAt));

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function restore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'restore', array());

        return parent::restore();
    }

    /**
     * {@inheritDoc}
     */
    public function isInTrash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isInTrash', array());

        return parent::isInTrash();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeaser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeaser', array());

        return parent::getTeaser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeaser($teaser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeaser', array($teaser));

        return parent::setTeaser($teaser);
    }

    /**
     * {@inheritDoc}
     */
    public function getLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead', array());

        return parent::getLead();
    }

    /**
     * {@inheritDoc}
     */
    public function setLead($lead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead', array($lead));

        return parent::setLead($lead);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', array());

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', array($content));

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDescription($metaDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDescription', array($metaDescription));

        return parent::setMetaDescription($metaDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescription', array());

        return parent::getMetaDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaKeywords($metaKeywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaKeywords', array($metaKeywords));

        return parent::setMetaKeywords($metaKeywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaKeywords', array());

        return parent::getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\Application\Sonata\MediaBundle\Entity\Media $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeroImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeroImage', array());

        return parent::getHeroImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeroImage(\Application\Sonata\MediaBundle\Entity\Media $heroImage = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeroImage', array($heroImage));

        return parent::setHeroImage($heroImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', array());

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorName', array());

        return parent::getAuthorName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor($author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', array($author));

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', array());

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setSource($source)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', array($source));

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttachments($attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttachments', array($attachments));

        return parent::setAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', array());

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachment(\AppBundle\Entity\PostAttachment $postAttachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachment', array($postAttachment));

        return parent::addAttachment($postAttachment);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedPosts', array());

        return parent::getRelatedPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedPosts($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedPosts', array($entities));

        return parent::setRelatedPosts($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedPosts($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedPosts', array($entity));

        return parent::addRelatedPosts($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedPosts($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedPosts', array($entity));

        return parent::removeRelatedPosts($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedNewsPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedNewsPosts', array());

        return parent::getRelatedNewsPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedPressReleases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedPressReleases', array());

        return parent::getRelatedPressReleases();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedInfographics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedInfographics', array());

        return parent::getRelatedInfographics();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedInfographics($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedInfographics', array($entities));

        return parent::setRelatedInfographics($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedInfographics($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedInfographics', array($entity));

        return parent::addRelatedInfographics($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedInfographics($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedInfographics', array($entity));

        return parent::removeRelatedInfographics($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedGalleries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedGalleries', array());

        return parent::getRelatedGalleries();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedGalleries($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedGalleries', array($entities));

        return parent::setRelatedGalleries($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedGalleries($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedGalleries', array($entity));

        return parent::addRelatedGalleries($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedGalleries($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedGalleries', array($entity));

        return parent::removeRelatedGalleries($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedVideos', array());

        return parent::getRelatedVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedVideos($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedVideos', array($entities));

        return parent::setRelatedVideos($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedVideos($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedVideos', array($entity));

        return parent::addRelatedVideos($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedVideos($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedVideos', array($entity));

        return parent::removeRelatedVideos($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedConstructions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedConstructions', array());

        return parent::getRelatedConstructions();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedConstructions($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedConstructions', array($entities));

        return parent::setRelatedConstructions($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedConstructions($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedConstructions', array($entity));

        return parent::addRelatedConstructions($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedConstructions($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedConstructions', array($entity));

        return parent::removeRelatedConstructions($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedMetroStations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedMetroStations', array());

        return parent::getRelatedMetroStations();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedMetroStations($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedMetroStations', array($entities));

        return parent::setRelatedMetroStations($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedMetroStations($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedMetroStations', array($entity));

        return parent::addRelatedMetroStations($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedMetroStations($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedMetroStations', array($entity));

        return parent::removeRelatedMetroStations($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedRoads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedRoads', array());

        return parent::getRelatedRoads();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedRoads($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedRoads', array($entities));

        return parent::setRelatedRoads($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedRoads($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedRoads', array($entity));

        return parent::addRelatedRoads($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedRoads($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedRoads', array($entity));

        return parent::removeRelatedRoads($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedDocuments', array());

        return parent::getRelatedDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedDocuments($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedDocuments', array($entities));

        return parent::setRelatedDocuments($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedDocuments($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedDocuments', array($entity));

        return parent::addRelatedDocuments($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedDocuments($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedDocuments', array($entity));

        return parent::removeRelatedDocuments($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelated', array());

        return parent::getRelated();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', array($tags));

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', array());

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishable($publishable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishable', array($publishable));

        return parent::setPublishable($publishable);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublishable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublishable', array());

        return parent::isPublishable();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishStartDate', array());

        return parent::getPublishStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishEndDate', array());

        return parent::getPublishEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishEndDate(\DateTime $publishEndDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishEndDate', array($publishEndDate));

        return parent::setPublishEndDate($publishEndDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setFeedable($feedable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeedable', array($feedable));

        return parent::setFeedable($feedable);
    }

    /**
     * {@inheritDoc}
     */
    public function isFeedable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFeedable', array());

        return parent::isFeedable();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishableInRss($publishableInRss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishableInRss', array($publishableInRss));

        return parent::setPublishableInRss($publishableInRss);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublishableInRss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublishableInRss', array());

        return parent::isPublishableInRss();
    }

    /**
     * {@inheritDoc}
     */
    public function setSearchable($searchable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearchable', array($searchable));

        return parent::setSearchable($searchable);
    }

    /**
     * {@inheritDoc}
     */
    public function isSearchable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSearchable', array());

        return parent::isSearchable();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelevantNewsShown($relevantNewsShown)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelevantNewsShown', array($relevantNewsShown));

        return parent::setRelevantNewsShown($relevantNewsShown);
    }

    /**
     * {@inheritDoc}
     */
    public function isRelevantNewsShown()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRelevantNewsShown', array());

        return parent::isRelevantNewsShown();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(\AppBundle\Entity\Embeddable\Address $address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeUnit', array());

        return parent::getAdministrativeUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeUnit($administrativeUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeUnit', array($administrativeUnit));

        return parent::setAdministrativeUnit($administrativeUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeArea', array());

        return parent::getAdministrativeArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getCityDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityDistrict', array());

        return parent::getCityDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isCommentsOpen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCommentsOpen', array());

        return parent::isCommentsOpen();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCommentsOpen($isCommentsOpen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCommentsOpen', array($isCommentsOpen));

        return parent::setIsCommentsOpen($isCommentsOpen);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($user));

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', array($user));

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', array($user));

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', array());

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', array());

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', array());

        return parent::isBlameable();
    }

    /**
     * {@inheritDoc}
     */
    public function getPriorityPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriorityPosition', array());

        return parent::getPriorityPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriorityPosition($priorityPosition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriorityPosition', array($priorityPosition));

        return parent::setPriorityPosition($priorityPosition);
    }

    /**
     * {@inheritDoc}
     */
    public function changePriority($newPriority, \AppBundle\Entity\Repository\PostRepository $postRepository)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'changePriority', array($newPriority, $postRepository));

        return parent::changePriority($newPriority, $postRepository);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityLock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityLock', array());

        return parent::getEntityLock();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityLock($entityLock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityLock', array($entityLock));

        return parent::setEntityLock($entityLock);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwners', array());

        return parent::getOwners();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwners($owners)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwners', array($owners));

        return parent::setOwners($owners);
    }

    /**
     * {@inheritDoc}
     */
    public function hasStroiMosOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasStroiMosOwner', array());

        return parent::hasStroiMosOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function hasOwner(\AppBundle\Entity\Owner $owner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasOwner', array($owner));

        return parent::hasOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileContent', array());

        return parent::getMobileContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileContent($mobileContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileContent', array($mobileContent));

        return parent::setMobileContent($mobileContent);
    }

}
