<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DecisionDocument extends \AppBundle\Entity\DecisionDocument implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'number', 'status', 'ApproveDate', 'id', 'files', 'title', 'content', 'metaDescription', 'metaKeywords', 'publishable', 'publishStartDate', 'publishEndDate', 'searchable', 'createdAt', 'updatedAt', 'relatedPosts', 'relatedInfographics', 'relatedGalleries', 'relatedVideos', 'relatedConstructions', 'relatedMetroStations', 'relatedRoads', 'relatedDocuments', 'createdBy', 'updatedBy', 'deletedBy', 'owners');
        }

        return array('__isInitialized__', 'number', 'status', 'ApproveDate', 'id', 'files', 'title', 'content', 'metaDescription', 'metaKeywords', 'publishable', 'publishStartDate', 'publishEndDate', 'searchable', 'createdAt', 'updatedAt', 'relatedPosts', 'relatedInfographics', 'relatedGalleries', 'relatedVideos', 'relatedConstructions', 'relatedMetroStations', 'relatedRoads', 'relatedDocuments', 'createdBy', 'updatedBy', 'deletedBy', 'owners');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DecisionDocument $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', array());

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', array($number));

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function isStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStatus', array());

        return parent::isStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getApproveDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApproveDate', array());

        return parent::getApproveDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setApproveDate($ApproveDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApproveDate', array($ApproveDate));

        return parent::setApproveDate($ApproveDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeName', array());

        return parent::getTypeName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', array());

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiles(\Doctrine\Common\Collections\ArrayCollection $files)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiles', array($files));

        return parent::setFiles($files);
    }

    /**
     * {@inheritDoc}
     */
    public function addFile(\AppBundle\Entity\DocumentHasMedia $file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFile', array($file));

        return parent::addFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', array());

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', array($content));

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDescription($metaDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDescription', array($metaDescription));

        return parent::setMetaDescription($metaDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescription', array());

        return parent::getMetaDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaKeywords($metaKeywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaKeywords', array($metaKeywords));

        return parent::setMetaKeywords($metaKeywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaKeywords', array());

        return parent::getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishable($publishable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishable', array($publishable));

        return parent::setPublishable($publishable);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublishable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublishable', array());

        return parent::isPublishable();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishStartDate', array());

        return parent::getPublishStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishStartDate(\DateTime $publishStartDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishStartDate', array($publishStartDate));

        return parent::setPublishStartDate($publishStartDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishEndDate', array());

        return parent::getPublishEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishEndDate(\DateTime $publishEndDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishEndDate', array($publishEndDate));

        return parent::setPublishEndDate($publishEndDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setSearchable($searchable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearchable', array($searchable));

        return parent::setSearchable($searchable);
    }

    /**
     * {@inheritDoc}
     */
    public function isSearchable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSearchable', array());

        return parent::isSearchable();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersistTimestampable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersistTimestampable', array());

        return parent::onPrePersistTimestampable();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdateTimestampable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdateTimestampable', array());

        return parent::onPreUpdateTimestampable();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedPosts', array());

        return parent::getRelatedPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedPosts($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedPosts', array($entities));

        return parent::setRelatedPosts($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedPosts($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedPosts', array($entity));

        return parent::addRelatedPosts($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedPosts($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedPosts', array($entity));

        return parent::removeRelatedPosts($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedNewsPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedNewsPosts', array());

        return parent::getRelatedNewsPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedPressReleases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedPressReleases', array());

        return parent::getRelatedPressReleases();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedInfographics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedInfographics', array());

        return parent::getRelatedInfographics();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedInfographics($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedInfographics', array($entities));

        return parent::setRelatedInfographics($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedInfographics($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedInfographics', array($entity));

        return parent::addRelatedInfographics($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedInfographics($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedInfographics', array($entity));

        return parent::removeRelatedInfographics($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedGalleries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedGalleries', array());

        return parent::getRelatedGalleries();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedGalleries($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedGalleries', array($entities));

        return parent::setRelatedGalleries($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedGalleries($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedGalleries', array($entity));

        return parent::addRelatedGalleries($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedGalleries($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedGalleries', array($entity));

        return parent::removeRelatedGalleries($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedVideos', array());

        return parent::getRelatedVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedVideos($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedVideos', array($entities));

        return parent::setRelatedVideos($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedVideos($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedVideos', array($entity));

        return parent::addRelatedVideos($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedVideos($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedVideos', array($entity));

        return parent::removeRelatedVideos($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedConstructions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedConstructions', array());

        return parent::getRelatedConstructions();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedConstructions($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedConstructions', array($entities));

        return parent::setRelatedConstructions($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedConstructions($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedConstructions', array($entity));

        return parent::addRelatedConstructions($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedConstructions($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedConstructions', array($entity));

        return parent::removeRelatedConstructions($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedMetroStations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedMetroStations', array());

        return parent::getRelatedMetroStations();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedMetroStations($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedMetroStations', array($entities));

        return parent::setRelatedMetroStations($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedMetroStations($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedMetroStations', array($entity));

        return parent::addRelatedMetroStations($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedMetroStations($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedMetroStations', array($entity));

        return parent::removeRelatedMetroStations($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedRoads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedRoads', array());

        return parent::getRelatedRoads();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedRoads($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedRoads', array($entities));

        return parent::setRelatedRoads($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedRoads($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedRoads', array($entity));

        return parent::addRelatedRoads($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedRoads($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedRoads', array($entity));

        return parent::removeRelatedRoads($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedDocuments', array());

        return parent::getRelatedDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedDocuments($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedDocuments', array($entities));

        return parent::setRelatedDocuments($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedDocuments($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedDocuments', array($entity));

        return parent::addRelatedDocuments($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedDocuments($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedDocuments', array($entity));

        return parent::removeRelatedDocuments($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelated', array());

        return parent::getRelated();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', array($tags));

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', array());

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($user));

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', array($user));

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', array($user));

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', array());

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', array());

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', array());

        return parent::isBlameable();
    }

    /**
     * {@inheritDoc}
     */
    public function getOwners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwners', array());

        return parent::getOwners();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwners($owners)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwners', array($owners));

        return parent::setOwners($owners);
    }

    /**
     * {@inheritDoc}
     */
    public function hasStroiMosOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasStroiMosOwner', array());

        return parent::hasStroiMosOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function hasOwner(\AppBundle\Entity\Owner $owner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasOwner', array($owner));

        return parent::hasOwner($owner);
    }

}
