<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SpotlightItem extends \AppBundle\Entity\SpotlightItem implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'uri', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'openInNewTab', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage1', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage2', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage3', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage4', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage5', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'post', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'gallery', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'video', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'infographics', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'construction', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'metro', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'road', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'page', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'position', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'publicationType', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'backgroundImage', 'id');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'uri', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'openInNewTab', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage1', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage2', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage3', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage4', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'carouselImage5', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'post', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'gallery', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'video', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'infographics', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'construction', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'metro', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'road', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'page', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'position', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'publicationType', '' . "\0" . 'AppBundle\\Entity\\SpotlightItem' . "\0" . 'backgroundImage', 'id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SpotlightItem $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getUri()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUri', array());

        return parent::getUri();
    }

    /**
     * {@inheritDoc}
     */
    public function setUri($uri)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUri', array($uri));

        return parent::setUri($uri);
    }

    /**
     * {@inheritDoc}
     */
    public function isOpenInNewTab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOpenInNewTab', array());

        return parent::isOpenInNewTab();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpenInNewTab($openInNewTab)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpenInNewTab', array($openInNewTab));

        return parent::setOpenInNewTab($openInNewTab);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPost', array());

        return parent::getPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setPost($post)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPost', array($post));

        return parent::setPost($post);
    }

    /**
     * {@inheritDoc}
     */
    public function getGallery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGallery', array());

        return parent::getGallery();
    }

    /**
     * {@inheritDoc}
     */
    public function setGallery($gallery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGallery', array($gallery));

        return parent::setGallery($gallery);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', array());

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', array($video));

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfographics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfographics', array());

        return parent::getInfographics();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfographics($infographics)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfographics', array($infographics));

        return parent::setInfographics($infographics);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstruction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstruction', array());

        return parent::getConstruction();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstruction($construction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstruction', array($construction));

        return parent::setConstruction($construction);
    }

    /**
     * {@inheritDoc}
     */
    public function getPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPage', array());

        return parent::getPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPage($page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPage', array($page));

        return parent::setPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetro', array());

        return parent::getMetro();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetro($metro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetro', array($metro));

        return parent::setMetro($metro);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoad', array());

        return parent::getRoad();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoad($road)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoad', array($road));

        return parent::setRoad($road);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', array());

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', array($position));

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function validate(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validate', array($context));

        return parent::validate($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeLabel', array());

        return parent::getTypeLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntity', array());

        return parent::getEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxPossiblePosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxPossiblePosition', array());

        return parent::getMaxPossiblePosition();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicationType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicationType', array());

        return parent::getPublicationType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicationType($publicationType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicationType', array($publicationType));

        return parent::setPublicationType($publicationType);
    }

    /**
     * {@inheritDoc}
     */
    public function isBackgroundImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBackgroundImage', array());

        return parent::isBackgroundImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setBackgroundImage($backgroundImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBackgroundImage', array($backgroundImage));

        return parent::setBackgroundImage($backgroundImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarouselImage1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarouselImage1', array());

        return parent::getCarouselImage1();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarouselImage1($carouselImage1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarouselImage1', array($carouselImage1));

        return parent::setCarouselImage1($carouselImage1);
    }

    /**
     * {@inheritDoc}
     */
    public function hasCarouselImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasCarouselImages', array());

        return parent::hasCarouselImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarouselImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarouselImages', array());

        return parent::getCarouselImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarouselImage5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarouselImage5', array());

        return parent::getCarouselImage5();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarouselImage5($carouselImage5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarouselImage5', array($carouselImage5));

        return parent::setCarouselImage5($carouselImage5);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarouselImage4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarouselImage4', array());

        return parent::getCarouselImage4();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarouselImage4($carouselImage4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarouselImage4', array($carouselImage4));

        return parent::setCarouselImage4($carouselImage4);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarouselImage3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarouselImage3', array());

        return parent::getCarouselImage3();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarouselImage3($carouselImage3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarouselImage3', array($carouselImage3));

        return parent::setCarouselImage3($carouselImage3);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarouselImage2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarouselImage2', array());

        return parent::getCarouselImage2();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarouselImage2($carouselImage2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarouselImage2', array($carouselImage2));

        return parent::setCarouselImage2($carouselImage2);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

}
