<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Construction extends \AppBundle\Entity\Construction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }





    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'areaOfTheTerritory', 'roominess', 'numberOfParkingPlaces', 'startYear', 'endYear', 'projectSeries', 'tour3D', 'projectDesigner', 'data', 'pendingData', 'customData', 'distance', 'point', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectId', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'uniqueId', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectUpdateDateTime', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'deleted', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectName', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectAddress', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'constructionParameterValues', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'planDateEnd', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'factDateEnd', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'planDateInput', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'factDateInput', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'planDateStart', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'factDateStart', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'new', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'updated', 'teaser', 'content', 'image', 'relatedPosts', 'relatedInfographics', 'relatedGalleries', 'relatedVideos', 'relatedConstructions', 'relatedMetroStations', 'relatedRoads', 'relatedDocuments', 'publishable', 'searchable', 'relevantNewsShown', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'administrativeUnit', 'metaDescription', 'metaKeywords', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'entityLock', 'panorama', 'organization', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'extraInformation', 'mobileContent');
        }

        return array('__isInitialized__', 'areaOfTheTerritory', 'roominess', 'numberOfParkingPlaces', 'startYear', 'endYear', 'projectSeries', 'tour3D', 'projectDesigner', 'data', 'pendingData', 'customData', 'distance', 'point', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectId', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'uniqueId', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectUpdateDateTime', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'deleted', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectName', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'objectAddress', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'constructionParameterValues', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'planDateEnd', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'factDateEnd', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'planDateInput', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'factDateInput', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'planDateStart', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'factDateStart', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'new', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'updated', 'teaser', 'content', 'image', 'relatedPosts', 'relatedInfographics', 'relatedGalleries', 'relatedVideos', 'relatedConstructions', 'relatedMetroStations', 'relatedRoads', 'relatedDocuments', 'publishable', 'searchable', 'relevantNewsShown', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'administrativeUnit', 'metaDescription', 'metaKeywords', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'entityLock', 'panorama', 'organization', '' . "\0" . 'AppBundle\\Entity\\Construction' . "\0" . 'extraInformation', 'mobileContent');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Construction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDistance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistance', array());

        return parent::getDistance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistance($distance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistance', array($distance));

        return parent::setDistance($distance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataField($field, $fallback = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataField', array($field, $fallback));

        return parent::getDataField($field, $fallback);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomData', array());

        return parent::getCustomData();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomData($customData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomData', array($customData));

        return parent::setCustomData($customData);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaOfTheTerritory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaOfTheTerritory', array());

        return parent::getAreaOfTheTerritory();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaOfTheTerritory($areaOfTheTerritory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaOfTheTerritory', array($areaOfTheTerritory));

        return parent::setAreaOfTheTerritory($areaOfTheTerritory);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoominess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoominess', array());

        return parent::getRoominess();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoominess($roominess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoominess', array($roominess));

        return parent::setRoominess($roominess);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberOfParkingPlaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberOfParkingPlaces', array());

        return parent::getNumberOfParkingPlaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberOfParkingPlaces($numberOfParkingPlaces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberOfParkingPlaces', array($numberOfParkingPlaces));

        return parent::setNumberOfParkingPlaces($numberOfParkingPlaces);
    }

    /**
     * {@inheritDoc}
     */
    public function setEndYearFromSoapResponse(\AppBundle\Soap\BusUgdMosRu\SoapResponse $response)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndYearFromSoapResponse', array($response));

        return parent::setEndYearFromSoapResponse($response);
    }

    /**
     * {@inheritDoc}
     */
    public function setEndYearFromBusResponse($response)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndYearFromBusResponse', array($response));

        return parent::setEndYearFromBusResponse($response);
    }

    /**
     * {@inheritDoc}
     */
    public function setStartYearFromBusResponse($response)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartYearFromBusResponse', array($response));

        return parent::setStartYearFromBusResponse($response);
    }

    /**
     * {@inheritDoc}
     */
    public function parsePlanDateFromBusResponse($response, $resource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'parsePlanDateFromBusResponse', array($response, $resource));

        return parent::parsePlanDateFromBusResponse($response, $resource);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectSeries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectSeries', array());

        return parent::getProjectSeries();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectSeries($projectSeries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectSeries', array($projectSeries));

        return parent::setProjectSeries($projectSeries);
    }

    /**
     * {@inheritDoc}
     */
    public function getTour3D()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTour3D', array());

        return parent::getTour3D();
    }

    /**
     * {@inheritDoc}
     */
    public function setTour3D(\Application\Sonata\MediaBundle\Entity\Media $tour3D = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTour3D', array($tour3D));

        return parent::setTour3D($tour3D);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectDesigner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectDesigner', array());

        return parent::getProjectDesigner();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectDesigner($projectDesigner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectDesigner', array($projectDesigner));

        return parent::setProjectDesigner($projectDesigner);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectUpdateDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectUpdateDateTime', array());

        return parent::getObjectUpdateDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getPendingData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPendingData', array());

        return parent::getPendingData();
    }

    /**
     * {@inheritDoc}
     */
    public function setPendingData($pendingData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPendingData', array($pendingData));

        return parent::setPendingData($pendingData);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectName', array());

        return parent::getObjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function assignObjectId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assignObjectId', array());

        return parent::assignObjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function isNewDataPending()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNewDataPending', array());

        return parent::isNewDataPending();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectId', array());

        return parent::getObjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function updateObjectName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateObjectName', array());

        return parent::updateObjectName();
    }

    /**
     * {@inheritDoc}
     */
    public function updateObjectAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateObjectAddress', array());

        return parent::updateObjectAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function updateUpdateDateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateUpdateDateTime', array());

        return parent::updateUpdateDateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function updateDeletedStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateDeletedStatus', array());

        return parent::updateDeletedStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', array());

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function acceptPendingData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'acceptPendingData', array());

        return parent::acceptPendingData();
    }

    /**
     * {@inheritDoc}
     */
    public function getSearchData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchData', array());

        return parent::getSearchData();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressText', array());

        return parent::getAddressText();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoPointCoordinatesInGeoJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoPointCoordinatesInGeoJson', array());

        return parent::getGeoPointCoordinatesInGeoJson();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoPolygonInGeoJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoPolygonInGeoJson', array());

        return parent::getGeoPolygonInGeoJson();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeoPointAsLonLatArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeoPointAsLonLatArray', array());

        return parent::getGeoPointAsLonLatArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getFunctionalPurpose()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFunctionalPurpose', array());

        return parent::getFunctionalPurpose();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeveloper()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeveloper', array());

        return parent::getDeveloper();
    }

    /**
     * {@inheritDoc}
     */
    public function getSourceOfFinance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSourceOfFinance', array());

        return parent::getSourceOfFinance();
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionStatus', array());

        return parent::getConstructionStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionStartYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionStartYear', array());

        return parent::getConstructionStartYear();
    }

    /**
     * {@inheritDoc}
     */
    public function getStartYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartYear', array());

        return parent::getStartYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartYear($startYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartYear', array($startYear));

        return parent::setStartYear($startYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionEndYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionEndYear', array());

        return parent::getConstructionEndYear();
    }

    /**
     * {@inheritDoc}
     */
    public function getEndYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndYear', array());

        return parent::getEndYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndYear($endYear)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndYear', array($endYear));

        return parent::setEndYear($endYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanDateEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanDateEnd', array());

        return parent::getPlanDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanDateEnd($planDateEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanDateEnd', array($planDateEnd));

        return parent::setPlanDateEnd($planDateEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactDateEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactDateEnd', array());

        return parent::getFactDateEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactDateEnd($factDateEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactDateEnd', array($factDateEnd));

        return parent::setFactDateEnd($factDateEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanDateInput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanDateInput', array());

        return parent::getPlanDateInput();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanDateInput($planDateInput)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanDateInput', array($planDateInput));

        return parent::setPlanDateInput($planDateInput);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactDateInput()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactDateInput', array());

        return parent::getFactDateInput();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactDateInput($factDateInput)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactDateInput', array($factDateInput));

        return parent::setFactDateInput($factDateInput);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanDateStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanDateStart', array());

        return parent::getPlanDateStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanDateStart($planDateStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanDateStart', array($planDateStart));

        return parent::setPlanDateStart($planDateStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactDateStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactDateStart', array());

        return parent::getFactDateStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setFactDateStart($factDateStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactDateStart', array($factDateStart));

        return parent::setFactDateStart($factDateStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomDataDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomDataDistrict', array());

        return parent::getCustomDataDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionStatusTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionStatusTranslations', array());

        return parent::getConstructionStatusTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoordinates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoordinates', array());

        return parent::getCoordinates();
    }

    /**
     * {@inheritDoc}
     */
    public function addConstructionParameterValue(\AppBundle\Entity\ConstructionParameterValue $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConstructionParameterValue', array($value));

        return parent::addConstructionParameterValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getConstructionParameterValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConstructionParameterValues', array());

        return parent::getConstructionParameterValues();
    }

    /**
     * {@inheritDoc}
     */
    public function setConstructionParameterValues($constructionParameterValues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConstructionParameterValues', array($constructionParameterValues));

        return parent::setConstructionParameterValues($constructionParameterValues);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConstructionParameterValue(\AppBundle\Entity\ConstructionParameterValue $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConstructionParameterValue', array($value));

        return parent::removeConstructionParameterValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoint', array());

        return parent::getPoint();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoint($point)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoint', array($point));

        return parent::setPoint($point);
    }

    /**
     * {@inheritDoc}
     */
    public function isImported()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isImported', array());

        return parent::isImported();
    }

    /**
     * {@inheritDoc}
     */
    public function isNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNew', array());

        return parent::isNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setNew($new)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNew', array($new));

        return parent::setNew($new);
    }

    /**
     * {@inheritDoc}
     */
    public function isUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUpdated', array());

        return parent::isUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueId', array());

        return parent::getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniqueId($uniqueId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniqueId', array($uniqueId));

        return parent::setUniqueId($uniqueId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeaser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeaser', array());

        return parent::getTeaser();
    }

    /**
     * {@inheritDoc}
     */
    public function setTeaser($teaser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTeaser', array($teaser));

        return parent::setTeaser($teaser);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', array());

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', array($content));

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\Application\Sonata\MediaBundle\Entity\Media $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedPosts', array());

        return parent::getRelatedPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedPosts($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedPosts', array($entities));

        return parent::setRelatedPosts($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedPosts($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedPosts', array($entity));

        return parent::addRelatedPosts($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedPosts($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedPosts', array($entity));

        return parent::removeRelatedPosts($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedNewsPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedNewsPosts', array());

        return parent::getRelatedNewsPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedPressReleases()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedPressReleases', array());

        return parent::getRelatedPressReleases();
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedInfographics()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedInfographics', array());

        return parent::getRelatedInfographics();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedInfographics($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedInfographics', array($entities));

        return parent::setRelatedInfographics($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedInfographics($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedInfographics', array($entity));

        return parent::addRelatedInfographics($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedInfographics($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedInfographics', array($entity));

        return parent::removeRelatedInfographics($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedGalleries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedGalleries', array());

        return parent::getRelatedGalleries();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedGalleries($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedGalleries', array($entities));

        return parent::setRelatedGalleries($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedGalleries($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedGalleries', array($entity));

        return parent::addRelatedGalleries($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedGalleries($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedGalleries', array($entity));

        return parent::removeRelatedGalleries($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedVideos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedVideos', array());

        return parent::getRelatedVideos();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedVideos($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedVideos', array($entities));

        return parent::setRelatedVideos($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedVideos($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedVideos', array($entity));

        return parent::addRelatedVideos($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedVideos($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedVideos', array($entity));

        return parent::removeRelatedVideos($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedConstructions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedConstructions', array());

        return parent::getRelatedConstructions();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedConstructions($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedConstructions', array($entities));

        return parent::setRelatedConstructions($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedConstructions($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedConstructions', array($entity));

        return parent::addRelatedConstructions($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedConstructions($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedConstructions', array($entity));

        return parent::removeRelatedConstructions($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedMetroStations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedMetroStations', array());

        return parent::getRelatedMetroStations();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedMetroStations($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedMetroStations', array($entities));

        return parent::setRelatedMetroStations($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedMetroStations($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedMetroStations', array($entity));

        return parent::addRelatedMetroStations($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedMetroStations($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedMetroStations', array($entity));

        return parent::removeRelatedMetroStations($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedRoads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedRoads', array());

        return parent::getRelatedRoads();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedRoads($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedRoads', array($entities));

        return parent::setRelatedRoads($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedRoads($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedRoads', array($entity));

        return parent::addRelatedRoads($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedRoads($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedRoads', array($entity));

        return parent::removeRelatedRoads($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelatedDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelatedDocuments', array());

        return parent::getRelatedDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelatedDocuments($entities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelatedDocuments', array($entities));

        return parent::setRelatedDocuments($entities);
    }

    /**
     * {@inheritDoc}
     */
    public function addRelatedDocuments($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRelatedDocuments', array($entity));

        return parent::addRelatedDocuments($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRelatedDocuments($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRelatedDocuments', array($entity));

        return parent::removeRelatedDocuments($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getRelated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRelated', array());

        return parent::getRelated();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishable($publishable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishable', array($publishable));

        return parent::setPublishable($publishable);
    }

    /**
     * {@inheritDoc}
     */
    public function isPublishable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPublishable', array());

        return parent::isPublishable();
    }

    /**
     * {@inheritDoc}
     */
    public function setSearchable($searchable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSearchable', array($searchable));

        return parent::setSearchable($searchable);
    }

    /**
     * {@inheritDoc}
     */
    public function isSearchable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSearchable', array());

        return parent::isSearchable();
    }

    /**
     * {@inheritDoc}
     */
    public function setRelevantNewsShown($relevantNewsShown)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRelevantNewsShown', array($relevantNewsShown));

        return parent::setRelevantNewsShown($relevantNewsShown);
    }

    /**
     * {@inheritDoc}
     */
    public function isRelevantNewsShown()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isRelevantNewsShown', array());

        return parent::isRelevantNewsShown();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeUnit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeUnit', array());

        return parent::getAdministrativeUnit();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrativeUnit($administrativeUnit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrativeUnit', array($administrativeUnit));

        return parent::setAdministrativeUnit($administrativeUnit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrativeArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrativeArea', array());

        return parent::getAdministrativeArea();
    }

    /**
     * {@inheritDoc}
     */
    public function getCityDistrict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityDistrict', array());

        return parent::getCityDistrict();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaDescription($metaDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaDescription', array($metaDescription));

        return parent::setMetaDescription($metaDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaDescription', array());

        return parent::getMetaDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetaKeywords($metaKeywords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetaKeywords', array($metaKeywords));

        return parent::setMetaKeywords($metaKeywords);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaKeywords', array());

        return parent::getMetaKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', array($user));

        return parent::setCreatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', array($user));

        return parent::setUpdatedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedBy($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedBy', array($user));

        return parent::setDeletedBy($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', array());

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', array());

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedBy', array());

        return parent::getDeletedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function isBlameable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isBlameable', array());

        return parent::isBlameable();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityLock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityLock', array());

        return parent::getEntityLock();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityLock($entityLock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityLock', array($entityLock));

        return parent::setEntityLock($entityLock);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityReference', array());

        return parent::getEntityReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getPanorama()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanorama', array());

        return parent::getPanorama();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanorama($panorama)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanorama', array($panorama));

        return parent::setPanorama($panorama);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganization()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganization', array());

        return parent::getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganization($organization)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganization', array($organization));

        return parent::setOrganization($organization);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraInformation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraInformation', array());

        return parent::getExtraInformation();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraInformation($extraInformation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraInformation', array($extraInformation));

        return parent::setExtraInformation($extraInformation);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileContent', array());

        return parent::getMobileContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileContent($mobileContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileContent', array($mobileContent));

        return parent::setMobileContent($mobileContent);
    }

}
