<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use AppBundle\Entity\MediaCategory;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Sonata\MediaBundle\Entity\BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var MediaCategory
     */
    protected $category;
    /**
     * @var MediaCategory
     */
    protected $copyright;

    /**
     * @var string
     */
    private $createCategory;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \AppBundle\Entity\MediaCategory
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param \AppBundle\Entity\MediaCategory $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }


    /**
     * @return string
     */
    public function getCreateCategory()
    {
        return $this->createCategory;
    }

    /**
     * @param string $createCategory
     */
    public function setCreateCategory($createCategory)
    {
        $this->createCategory = $createCategory;
    }

    /**
     * @param LifecycleEventArgs $eventArgs
     */
    public function createCategory(LifecycleEventArgs $eventArgs)
    {
        if (!$this->createCategory) {
            return;
        }

        $newCategory = new MediaCategory();
        $newCategory->setTitle($this->createCategory);
        $newCategory->setParent($this->getCategory());
        $this->setCategory($newCategory);
    }

    /**
     * @param \AppBundle\Entity\MediaCategory $copyright
     */
    public function setCopyright($copyright)
    {
        $this->copyright = $copyright;
    }


    /**
     * @return string
     */
    public function getCopyright()
    {
        return $this->copyright;
    }
}
