imports:
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services/services.yml }
    - { resource: include/config_sonata_admin.yml }
    - { resource: include/config_sonata_media.yml }
    - { resource: include/config_sonata_seo.yml }
    - { resource: include/config_sonata_block.yml }
    - { resource: include/config_amg.yml }
    - { resource: include/config_elastica.yml }
    - { resource: include/config_liip_imagine.yml }
    - { resource: include/assets_version.yml }

parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["en"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true, enabled: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: "%trusted_proxies%"
    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions'
        cookie_secure: true
        cookie_samesite: 'lax'
    fragments:       ~
    http_method_override: true
    assets:
        version: "%assets_version%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'AmgPageBundle:Admin:Form/page_tree_widget.html.twig'
            - ':Admin:Form/hyperlink.html.twig'
            - ':Admin:Form/address.html.twig'
            - ':Admin:Form/copy_content_button.html.twig'
            - ':Admin:Form/geopoint.html.twig'
            - ':Admin:Form/construction_data_text.html.twig'
            - ':Admin:Form/construction_data_choice.html.twig'
            - ':Admin:Form/construction_data_geo_point.html.twig'
            - ':Admin:Form/construction_data_geo_polygon.html.twig'
            - ':Admin:Form/menu_tree_widget.html.twig'
            - ':Admin:Form/media_category_tree.html.twig'
            - ':Admin:Form/media_collection.html.twig'
            - ':Admin:Form/media_list.html.twig'
            - ':Admin:Form/secret_link.html.twig'
            - ':Admin:Form/image_type_extension.html.twig'
            - ':Admin:Form/collection_list.html.twig'
            - 'SonataCoreBundle:Form:datepicker.html.twig'
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - ':Admin:Form/gif_generator.html.twig'
            - ':Form:re_captcha.html.twig'

    globals:
        full_frontend: %full_frontend%
        new_design: false
        sendpulse_website_id: %sendpulse_website_id%
        sendsay_account: %sendsay_account%
        noindex: false
        gg_recaptcha_site_key: %google_recaptcha_site_key%
        yandex_captcha_site_key: %yandex_captcha_site_key%
    date:
        timezone: Europe/Moscow

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [] #todo: remove, ['AppBundle', 'FOSCommentBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            formatter: "compressed"
            preserve_comments: false
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
            multipolygon: CrEOF\Spatial\DBAL\Types\Geometry\MultiPolygonType
            geometry: CrEOF\Spatial\DBAL\Types\GeometryType
            point: CrEOF\Spatial\DBAL\Types\Geometry\PointType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy:      app.doctrine.orm.naming_strategy
                auto_mapping: true
                default_repository_class: Happyr\DoctrineSpecification\EntitySpecificationRepository
                filters:
                    publishable:
                        class: AppBundle\DoctrineFilter\Publishable
                        enabled: true
                    publishing_period:
                        class: AppBundle\DoctrineFilter\PublishingPeriod
                        enabled: true
                    not_moved_to_trash:
                        class: AppBundle\DoctrineFilter\NotMovedToTrash
                        enabled: true
                dql:
                    numeric_functions:
                        st_intersects: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STIntersects
                        geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                        astext: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\AsText
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                        is_bundle: false
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            timestampable: true
            sortable: true
            tree: true
            sluggable: true
            loggable: true

fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     Application\Sonata\UserBundle\Entity\User

    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager

    service:
        user_manager: sonata.user.orm.user_manager

    resetting:
        email:
            from_email:
                address:              %mailer_sender_address%
                sender_name:          %mailer_sender_name%

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      %mailer_port%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%
    delivery_address: %mailer_delivery_address%
    sender_address: %mailer_sender_address%
    spool:
        type: file
        path: %mailer_spool_path%

ivory_ck_editor:
    default_config: default
    plugins:
        fakeobjects:
            path: "/js/ckeditor/plugins/fakeobjects/"
            filename: "plugin.js"
        galleryplugin:
            path: "/js/ckeditor/plugins/galleryplugin/"
            filename: "galleryplugin.js"
        photo_lenta_grid:
            path: "/js/ckeditor/plugins/photo_lenta_grid/"
            filename: "plugin.js"
        twenty_twenty:
            path: "/js/ckeditor/plugins/twenty_twenty/"
            filename: "plugin.js"
        infographics:
            path: "/js/ckeditor/plugins/infographics/"
            filename: "plugin.js"
        organizationlink:
            path: "/js/ckeditor/plugins/organizationlink/"
            filename: "plugin.js"
        contactpersonlink:
            path: "/js/ckeditor/plugins/contactpersonlink/"
            filename: "plugin.js"
        youtube:
            path: "/js/ckeditor/plugins/youtube/"
            filename: "plugin.js"
        banner:
            path: "/js/ckeditor/plugins/banner/"
            filename: "plugin.js"
        quote:
            path: "/js/ckeditor/plugins/quote/"
            filename: "plugin.js"
        citydistrict_block:
            path: "/js/ckeditor/plugins/citydistrict_block/"
            filename: "plugin.js"
        keystrokes:
            path: "/js/ckeditor/plugins/keystrokes/"
            filename: "plugin.js"
    configs:
        default:
            title: ""
            contentsCss: /css/admin/ckeditor.css
            bodyClass: news-wrapper__content
            extraPlugins: "fakeobjects,galleryplugin,photo_lenta_grid,infographics,twenty_twenty,organizationlink,contactpersonlink,youtube,banner,quote,citydistrict_block,keystrokes"
            width: 740px
            height: 600px
            toolbar:
                - {name: document, items: ['Source', 'Print']}
                - {name: clipboard, items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']}
                - {name: basicstyles, items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']}
                - {name: paragraph, items: [ 'NumberedList', 'BulletedList', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', '-', 'Outdent', 'Indent' ] }
                - {name: formats, items: ['Format', 'Font', 'FontSize', 'TextColor']}
                - {name: insert, items: [ 'Table', 'SpecialChar'] }
                - {name: links, items: ['Link', 'Unlink', 'Anchor']}
                - {name: customlinks, items: ['OrganizationLink', 'ContactPersonLink']}
                - {name: mediainsert, items: [ 'Image', 'Youtube', 'Gallery', 'PhotoLentaGrid', 'TwentyTwenty', 'Banner', 'Quote', 'FaqBlock', 'CityDistrictBlock', 'Infographics' ] }
                - {name: styles, items: [ 'Styles' ] }
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
                context: main_image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.image
                context: main_image
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: main_image
            allowedContent: true
#            allowedContent: "video[*](*){*}; source[*](*){*}; style[*](*){*}; span[*](*){*}; h1; h4; pre; iframe[*](*){*}; table[*](*){*}; td[*](*){*}; tr[*](*){*}; p[*](*){*}; a[*](*){*}; div[*](*); img[*](*); strong; em; u; sup; sub; h2; h3; br; ul[*](*){*}; ol; li[*](*); blockquote[*](*)"
#            disallowedContent: "*{line*}"
            stylesSet: "custom_styles:/js/ckeditor/plugins/stylescombo/styles.js"
        page:
            title: ""
            contentsCss: /css/admin/ckeditor.css
            bodyClass: static-page
            extraPlugins: "fakeobjects,galleryplugin,photo_lenta_grid,infographics,twenty_twenty,organizationlink,contactpersonlink,youtube,banner,quote,citydistrict_block,keystrokes"
            width: 990px
            height: 600px
            toolbar:
                - {name: document, items: ['Source', 'Print']}
                - {name: clipboard, items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']}
                - {name: basicstyles, items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']}
                - {name: paragraph, items: [ 'NumberedList', 'BulletedList', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', '-', 'Outdent', 'Indent' ] }
                - {name: formats, items: ['Format', 'Font', 'FontSize', 'TextColor']}
                - {name: insert, items: [ 'Table', 'SpecialChar'] }
                - {name: links, items: ['Link', 'Unlink', 'Anchor']}
                - {name: customlinks, items: ['OrganizationLink', 'ContactPersonLink']}
                - {name: mediainsert, items: [ 'Image', 'Youtube', 'Gallery', 'PhotoLentaGrid', 'TwentyTwenty', 'Banner', 'Quote', 'FaqBlock', 'CityDistrictBlock', 'Infographics'] }
                - {name: styles, items: [ 'Styles' ] }
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
                context: main_image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.image
                context: main_image
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: main_image
            allowedContent: true
#            allowedContent: "video[*](*){*}; source[*](*){*}; style[*](*){*}; span[*](*){*}; h1; h4; pre; iframe[*](*){*}; table[*](*){*}; td[*](*){*}; tr[*](*){*}; p[*](*){*}; a[*](*){*}; div[*](*); img[*](*); strong; em; u; sup; sub; h2; h3; br; ul[*](*){*}; ol; li[*](*); blockquote[*](*)"
#            disallowedContent: "*{line*}"
            stylesSet: "custom_styles:/js/ckeditor/plugins/stylescombo/styles.js"

        currently:
            title: ""
            contentsCss: /css/admin/ckeditor.css
            bodyClass: now-block container__full
            width: 990px
            height: 300px
            toolbar:
                - {name: document, items: ['Source']}
                - {name: clipboard, items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']}
                - {name: basicstyles, items: ['Bold', 'Italic', 'RemoveFormat']}
                - {name: formats, items: ['Format']}
                - {name: insert, items: [ 'SpecialChar'] }
                - {name: links, items: ['Link', 'Unlink']}
                - {name: customlinks, items: ['OrganizationLink', 'ContactPersonLink']}
            allowedContent: 'p;h4;a[href]'

#fos_comment:
#    db_driver: orm
#    class:
#        model:
#            comment: Application\FOS\CommentBundle\Entity\Comment
#            thread: Application\FOS\CommentBundle\Entity\Thread
#    acl: true
#    service:
#        acl:
#            thread: fos_comment.acl.thread.roles
#            comment: fos_comment.acl.comment.roles
#            vote: fos_comment.acl.vote.roles
#        form_factory:
#            comment: fos_comment.form_factory.comment.default
#    form:
#        comment:
#            type: app_comment
#            name: app_comment
#    acl_roles:
#        comment:
#            create: ROLE_USER
#            view: IS_AUTHENTICATED_ANONYMOUSLY
#            edit: ROLE_SUPERADMIN
#            delete: ROLE_SUPERADMIN
#        thread:
#            create: IS_AUTHENTICATED_ANONYMOUSLY
#            view: IS_AUTHENTICATED_ANONYMOUSLY
#            edit: ROLE_SUPERADMIN
#            delete: ROLE_SUPERADMIN
##        vote:
##            create: IS_AUTHENTICATED_ANONYMOUSLY
##            view: IS_AUTHENTICATED_ANONYMOUSLY
##            edit: ROLE_ADMIN
##            delete: ROLE_ADMIN
presta_sitemap:
    timetolive: 3600
    route_annotation_listener: false

#disabled extra features
#hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
#    firewall_name: main
#    resource_owners:
#        vkontakte:
#            type:                vkontakte
#            client_id:           %vkontakte.client_id%
#            client_secret:       %vkontakte.client_secret%
#            scope: email
#        facebook:
#            type:                facebook
#            client_id:           %facebook.client_id%
#            client_secret:       %facebook.client_secret%
#            scope: email
#        google:
#            type:                google
#            client_id:           %google.client_id%
#            client_secret:       %google.client_secret%
#            scope:               "email profile"
#        login_mos_ru:
#            type:                oauth2
#            client_id:           %login_mos_ru.client_id%
#            client_secret:       %login_mos_ru.client_secret%
#            access_token_url:    https://oauth.mos.ru/eaiditoauthweb/oauth/token
#            authorization_url:   https://oauth.mos.ru/eaiditoauthweb/oauth/authorize
#            infos_url:           https://oauth.mos.ru/eaiditoauthweb/oauth/users/data
#            scope:               ~
#            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
#            paths:
#                identifier: id
#                email:      email
#                nickname:   alias
#                firstname:  firstname
#                lastname:   lastname
#                realname:   [lastname, firstname]

#    fosub:
#        username_iterations: 30
#
#        properties:
#            vkontakte: vkontakteUid
#            google: gplusUid
#            facebook: facebookUid
#            login_mos_ru: loginMosUid

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis_dsn%'
            logging: '%kernel.debug%'
        api_cache:
            type: predis
            alias: api_cache
            dsn: '%redis_dsn_construction%'
            logging: '%kernel.debug%'

jms_serializer:
    visitors:
        json:
            options: 256

stroi_mobile:
    entity_manager: default



