imports:
  - resource: config.yml
  - resource: include/nelmio_cors.yml

doctrine:
  orm:
    metadata_cache_driver:
      type: service
      id: doctrine_apc_cache
    result_cache_driver:
      type: memcache
      host: "%session_memcached_host%"
      port: "%session_memcached_port%"
      instance_class: Memcache
    query_cache_driver:
      type: service
      id: doctrine_apc_cache

monolog:
  handlers:
    main:
      type: stream
      path: "/var/logs/dev.log"
      level: debug
    console:
      type: console
      bubble: false
      verbosity_levels:
        VERBOSITY_VERBOSE: INFO
        VERBOSITY_VERY_VERBOSE: DEBUG
      channels:
        - doctrine
    console_very_verbose:
      type: console
      bubble: false
      verbosity_levels:
        VERBOSITY_VERBOSE: NOTICE
        VERBOSITY_VERY_VERBOSE: NOTICE
        VERBOSITY_DEBUG: DEBUG
      channels:
        - doctrine

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler:
    only_exceptions: false


web_profiler:
  toolbar: true
  intercept_redirects: false









assetic:
  use_controller: true

#swiftmailer:
#    delivery_address: me@example.com



