security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_NOTIFICATION_SENDER
            #todo: disabled extra features
#            - ROLE_EVENT_MODERATOR

        #todo: remove on extra remove
        ROLE_VIP_JOURNALIST: [ROLE_JOURNALIST]
        ROLE_JOURNALIST: []
        ROLE_EVENT_MODERATOR: []
        ROLE_NOTIFICATION_SENDER: []

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                success_handler: app.security.success_handler
                failure_handler: app.security.failure_handler
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /admin/dashboard
            logout:
                path:           /admin/logout
                target:         /admin/login
                success_handler: app.security.logout_success_handler
            anonymous:          true
            remember_me:
                key:            "%secret%"
                lifetime:       2678400 # 31 days in seconds
                path:           /
                domain:         ~ # Defaults to the current domain from $_SERVER
            switch_user: true

        # -> end custom configuration

        # defaut login area for standard users

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle

        main:
            pattern:             .*
            anonymous: true
            context:             user
#            form_login:
#                provider:       fos_userbundle
#                login_path:     /login
#                use_forward:    false
#                check_path:     /login_check
#                failure_path:   null
#            logout:             true
#            remember_me:
#                key:            "%secret%"
#                lifetime:       2678400 # 31 days in seconds
#                path:           /
#                domain:         ~ # Defaults to the current domain from $_SERVER
#            oauth:
#                resource_owners:
#                    facebook:           "/login/check-facebook"
#                    google:             "/login/check-google"
#                    vkontakte:          "/login/check-vkontakte"
#                    login_mos_ru:       "/login/login_mos_ru"
#                login_path:        /login
#                use_forward:       false
#                failure_path:      /login
#
#                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge
            switch_user: true

    access_control:
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }

#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # URL of FOSUserBundle which need to be available to anonymous users
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/profile, role: ROLE_USER }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
